const $=s=>document.querySelector(s), tbody=id=>document.querySelector(`#${id} tbody`);let sheets=[],parts=[],layouts=[],activeDragCancel=null,placementCandidate=null,placementSelection=null,pieceNoticeTimer=null;
const settingsPanel=$('#settingsPanel'),closeSettings=()=>{settingsPanel.classList.add('hidden');settingsPanel.classList.remove('settingsOpen')};$('#settingsBtn').onclick=()=>{settingsPanel.classList.remove('hidden');settingsPanel.classList.add('settingsOpen')};$('#closeSettings').onclick=closeSettings;document.addEventListener('click',e=>{if(!settingsPanel.classList.contains('hidden')&&!e.target.closest('#settingsPanel')&&!e.target.closest('#settingsBtn'))closeSettings()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!settingsPanel.classList.contains('hidden'))closeSettings()});
function materialOptions(value){let names=[...new Set(sheets.map(s=>s.material).filter(Boolean))];if(value&&!names.includes(value))names.unshift(value);return names.map(v=>`<option value="${v}" ${v===value?'selected':''}>${v}</option>`).join('')}
function row(type,x={}){let tr=document.createElement('tr');tr.dataset.type=type;let cells=type==='sheet'?`<td><input data-k="material" list="materialList" value="${x.material||'ЛДСП'}"></td><td><input data-k="length" value="${x.length||2800}"></td><td><input data-k="width" value="${x.width||2070}"></td><td><input data-k="qty" value="${x.qty||1}"></td>`:`<td class="partNumber"></td><td><input data-k="name" value="${x.name||'Новая деталь'}"></td><td><select data-k="material">${materialOptions(x.material||sheets[0]?.material||'ЛДСП')}</select></td><td><input data-k="length" value="${x.length||600}"></td><td><input data-k="width" value="${x.width||400}"></td><td><input data-k="qty" value="${x.qty||1}"></td><td><select data-k="rotate"><option value="1" ${x.rotate!==false?'selected':''}>Да</option><option value="0" ${x.rotate===false?'selected':''}>Нет</option></select></td><td><input data-k="rotateGroup" value="${x.rotateGroup||''}" placeholder="Например A" title="Одинаковое значение объединяет детали в группу совместного поворота"></td>`;tr.innerHTML=cells+`<td><button class="del">×</button></td>`;tr.querySelector('.del').onclick=()=>{tr.remove();sync();refreshMaterialControls()};return tr}
function sync(){tbody('parts').querySelectorAll('.partNumber').forEach((cell,i)=>cell.textContent=i+1);sheets=[...tbody('sheets').children].map(tr=>Object.fromEntries([...tr.querySelectorAll('[data-k]')].map(i=>[i.dataset.k,i.value])));parts=[...tbody('parts').children].map(tr=>{let o=Object.fromEntries([...tr.querySelectorAll('[data-k]')].map(i=>[i.dataset.k,i.value]));o.rotate=o.rotate==='1';return o});localStorage.cutMvp=JSON.stringify({sheets,parts})}
function refreshMaterialControls(){sync();let list=document.querySelector('#materialList');if(!list){list=document.createElement('datalist');list.id='materialList';document.body.append(list)}let names=[...new Set(sheets.map(s=>s.material).filter(Boolean))];list.innerHTML=names.map(v=>`<option value="${v}">`).join('');tbody('parts').querySelectorAll('select[data-k="material"]').forEach(sel=>{let old=sel.value;sel.innerHTML=materialOptions(old);sel.value=old})}
function load(d){tbody('sheets').innerHTML='';tbody('parts').innerHTML='';(d.sheets||[]).forEach(x=>tbody('sheets').append(row('sheet',x)));sync();(d.parts||[]).forEach(x=>tbody('parts').append(row('part',x)));refreshMaterialControls()}
$('#addSheet').onclick=()=>{tbody('sheets').append(row('sheet'));refreshMaterialControls()};$('#addStock').onclick=()=>{tbody('sheets').append(row('sheet',{length:1000,width:500,qty:1,material:'Остаток'}));refreshMaterialControls()};$('#addPart').onclick=()=>{tbody('parts').append(row('part'));sync()};document.addEventListener('input',e=>{sync();if(e.target.closest('#sheets'))refreshMaterialControls()});
function pieceElement(p,containerW,containerH,source){let d=document.createElement('div');d.className='piece';d.textContent=`${p.name} ${p.length}×${p.width}`;d.title=`${p.name}: ${p.length} × ${p.width} мм`;d.draggable=false;d.dataset.pieceId=p.id||'';d.dataset.source=source||'unplaced';d.style.left=(p.x||0)/containerW*100+'%';d.style.top=(p.y||0)/containerH*100+'%';d.style.width=p.length/containerW*100+'%';d.style.height=p.width/containerH*100+'%';if(source==='unplaced')d.addEventListener('pointerdown',e=>{if(e.button!==0)return;e.preventDefault();let board=d.parentElement,r=board.getBoundingClientRect(),dr=d.getBoundingClientRect(),sx=e.clientX,sy=e.clientY,dx=e.clientX-dr.left,dy=e.clientY-dr.top,ox=p.x||0,oy=p.y||0;d.classList.add('dragging');d.style.position='fixed';d.style.zIndex='9999';d.style.width=dr.width+'px';d.style.height=dr.height+'px';d.style.left=dr.left+'px';d.style.top=dr.top+'px';const move=q=>{p.x=ox+(q.clientX-sx)/r.width*containerW;p.y=oy+(q.clientY-sy)/r.height*containerH;d.style.left=q.clientX-dx+'px';d.style.top=q.clientY-dy+'px'};const reset=()=>{d.style.position='';d.style.zIndex='';d.style.width='';d.style.height='';d.style.left=p.x/containerW*100+'%';d.style.top=p.y/containerH*100+'%'};const stop=q=>{document.removeEventListener('pointermove',move);document.removeEventListener('pointerup',stop);document.removeEventListener('pointercancel',stop);d.classList.remove('dragging');let target=q&&document.elementFromPoint(q.clientX,q.clientY)?.closest('.sheet');if(target&&bestResult){let s=allSheetByIndex(target.dataset.sheetIndex),tr=target.getBoundingClientRect(),x=(q.clientX-tr.left)/tr.width*s.length-p.length/2,y=(q.clientY-tr.top)/tr.height*s.width-p.width/2;x=Math.max(0,Math.min(s.length-p.length,x));y=Math.max(0,Math.min(s.width-p.width,y));if(canDrop(s,p,x,y)){reset();s.placed.push({...p,x,y});bestResult.unplaced=bestResult.unplaced.filter(z=>z.id!==p.id);layouts=bestResult.layouts;render(bestResult.all,bestResult.unplaced);status.textContent=`Деталь «${p.name}» перемещена на лист.`;return}status.textContent='Деталь нельзя разместить в выбранной позиции.'}reset();bestResult.manual=true;status.textContent=`Позиция детали «${p.name}» изменена.`};document.addEventListener('pointermove',move);document.addEventListener('pointerup',stop);document.addEventListener('pointercancel',stop)});return d}
function allSheetByIndex(i){return bestResult?.all.find((s,n)=>n===Number(i))}
document.addEventListener('pointerup',()=>{let d=document.querySelector('.piece.dragging');if(d)d.style.pointerEvents='none';setTimeout(()=>document.querySelectorAll('.piece').forEach(x=>x.style.removeProperty('pointer-events')),0)},true);
function removePiece(list,p){let i=list.findIndex(x=>x===p||x.id===p.id);if(i>=0)list.splice(i,1)}
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function pieceNumber(p){return Number.isInteger(p.partNo)&&p.partNo>0?p.partNo:Number(p.id?.match(/^p(\d+)-/)?.[1])+1||''}
function pieceCount(p){let match=p.id?.match(/^p\d+-(\d+)$/),index=Number.isInteger(p.partIndex)?p.partIndex:match?Number(match[1])+1:0,qty=Number.isInteger(p.partQty)?p.partQty:Number(parts[pieceNumber(p)-1]?.qty)||0;return qty>1&&index>0?`${index}/${qty}`:''}
function pieceLabels(d,p,source,transposed=false){let no=source==='sheet'?pieceNumber(p):'',count=source==='sheet'?pieceCount(p):'',group=String(p.rotateGroup||'').trim(),horizontal=transposed?p.width:p.length,vertical=transposed?p.length:p.width;d.innerHTML=`${no?`<span class="pieceNo">${no}</span>`:''}${group?`<span class="pieceGroup">${escapeHtml(group)}</span>`:''}<span class="pieceName">${escapeHtml(p.name)}</span>${count?`<span class="pieceCount">${count}</span>`:''}<span class="pieceLength">${horizontal}</span><span class="pieceWidth">${vertical}</span>`}
function objectCanDrop(s,p,x,y){const k=+$('#kerf').value||0,m=+$('#margin').value||0;if(!s||p.material!==s.material||x<m||y<m||x+p.length>s.length-m||y+p.width>s.width-m)return false;return !s.placed.some(q=>q.id!==p.id&&x<q.x+q.length+k&&x+p.length+k>q.x&&y<q.y+q.width+k&&y+p.width+k>q.y)}
function pieceElement(p,containerW,containerH,source){let d=document.createElement('div');d.className='piece';d.textContent=`${p.name} ${p.length}×${p.width}`;d.title=`${p.name}: ${p.length} × ${p.width} мм`;d.dataset.pieceId=p.id||'';d.style.left=(p.x||0)/containerW*100+'%';d.style.top=(p.y||0)/containerH*100+'%';d.style.width=p.length/containerW*100+'%';d.style.height=p.width/containerH*100+'%';d.addEventListener('pointerdown',e=>{if(e.button!==0||!bestResult)return;e.preventDefault();let rect=d.getBoundingClientRect(),dx=e.clientX-rect.left,dy=e.clientY-rect.top,sourceSheet=source==='sheet'?bestResult.all.find(s=>s.placed.some(q=>q===p||q.id===p.id)):null,ghost=d.cloneNode(true);ghost.classList.add('dragGhost');ghost.style.position='fixed';ghost.style.left=rect.left+'px';ghost.style.top=rect.top+'px';ghost.style.width=rect.width+'px';ghost.style.height=rect.height+'px';ghost.style.zIndex='10000';ghost.style.pointerEvents='none';document.body.append(ghost);d.style.visibility='hidden';const move=q=>{ghost.style.left=q.clientX-dx+'px';ghost.style.top=q.clientY-dy+'px'};const finish=q=>{document.removeEventListener('pointermove',move);document.removeEventListener('pointerup',finish);document.removeEventListener('pointercancel',finish);let hit=q&&document.elementFromPoint(q.clientX,q.clientY),sheetEl=hit?.closest('.sheet'),freeEl=hit?.closest('#unplaced'),moved=false;if(sheetEl){let s=allSheetByIndex(sheetEl.dataset.sheetIndex),sr=sheetEl.getBoundingClientRect(),x=(q.clientX-dx-sr.left)/sr.width*s.length,y=(q.clientY-dy-sr.top)/sr.height*s.width;x=Math.max(+$('#margin').value||0,Math.min(s.length-p.length-(+$('#margin').value||0),x));y=Math.max(+$('#margin').value||0,Math.min(s.width-p.width-(+$('#margin').value||0),y));if(objectCanDrop(s,p,x,y)){if(sourceSheet)removePiece(sourceSheet.placed,p);else removePiece(bestResult.unplaced,p);s.placed.push({...p,x,y});moved=true;status.textContent=`Деталь «${p.name}» размещена на материале.`}else status.textContent='Здесь деталь разместить нельзя: место занято, не совпадает материал или нарушены границы.'}else if(freeEl&&sourceSheet){removePiece(sourceSheet.placed,p);let board=$('#unplacedBoard'),br=board.getBoundingClientRect(),ref=layouts[0]||bestResult.all[0],scale=ref?(document.querySelector('.sheet')?.getBoundingClientRect().width||306)/ref.length:.2,x=Math.max(0,(q.clientX-dx-br.left)/scale),y=Math.max(0,(q.clientY-dy-br.top)/scale);bestResult.unplaced.push({...p,x,y});moved=true;status.textContent=`Деталь «${p.name}» снята с материала.`}ghost.remove();d.style.visibility='';if(moved){bestResult.manual=true;layouts=bestResult.all.filter(s=>s.placed.length);bestResult.layouts=layouts;render(bestResult.all,bestResult.unplaced)}};document.addEventListener('pointermove',move);document.addEventListener('pointerup',finish);document.addEventListener('pointercancel',finish)});return d}
function canDrop(s,p,x,y){const k=+$('#kerf').value||0,m=+$('#margin').value||0;if(p.material!==s.material||x<m||y<m||x+p.length>s.length-m||y+p.width>s.width-m)return false;return !s.placed.some(q=>x<q.x+q.length+k&&x+p.length+k>q.x&&y<q.y+q.width+k&&y+p.width+k>q.y)}
function enableSheetDrop(el,s){el.dataset.sheetIndex=bestResult?.all.indexOf(s);el.addEventListener('dragover',e=>{e.preventDefault();e.dataTransfer.dropEffect='move';el.classList.add('dropTarget')});el.addEventListener('dragleave',()=>el.classList.remove('dropTarget'));el.addEventListener('drop',e=>{e.preventDefault();el.classList.remove('dropTarget');let id=e.dataTransfer.getData('text/plain'),p=bestResult?.unplaced.find(x=>x.id===id);if(!p)return;let r=el.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*s.length-p.length/2,y=(e.clientY-r.top)/r.height*s.width-p.width/2;x=Math.max(0,Math.min(s.length-p.length,x));y=Math.max(0,Math.min(s.width-p.width,y));if(!canDrop(s,p,x,y)){status.textContent='Деталь нельзя разместить: проверьте материал, границы или пересечение.';return}s.placed.push({...p,x,y});bestResult.unplaced=bestResult.unplaced.filter(q=>q.id!==id);layouts=bestResult.layouts;render(bestResult.all,bestResult.unplaced);status.textContent=`Деталь «${p.name}» перемещена на лист.`})}
function sheetIsTransposed(s){return s.width>s.length}
function sheetPointAt(s,sheetEl,left,top,p={length:0}){let r=sheetEl.getBoundingClientRect(),u=(left-r.left)/r.width,v=(top-r.top)/r.height;return sheetIsTransposed(s)?{x:s.length-v*s.length-p.length,y:u*s.width}:{x:u*s.length,y:v*s.width}}
function sheetClickPoint(s,sheetEl,e){return sheetPointAt(s,sheetEl,e.clientX,e.clientY)}
function setGhostOnSheet(ghost,s,sr,pos,p){if(sheetIsTransposed(s)){ghost.style.left=sr.left+pos.y/s.width*sr.width+'px';ghost.style.top=sr.top+(s.length-pos.x-p.length)/s.length*sr.height+'px';ghost.style.width=p.width/s.width*sr.width+'px';ghost.style.height=p.length/s.length*sr.height+'px'}else{ghost.style.left=sr.left+pos.x/s.length*sr.width+'px';ghost.style.top=sr.top+pos.y/s.width*sr.height+'px';ghost.style.width=p.length/s.length*sr.width+'px';ghost.style.height=p.width/s.width*sr.height+'px'}}
function snapPlacement(s,p,rawX,rawY,sheetEl){
 const k=+$('#kerf').value||0,m=+$('#margin').value||0,scale=sheetEl.getBoundingClientRect().width/(sheetIsTransposed(s)?s.width:s.length),threshold=24/scale;
 const clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
 rawX=clamp(rawX,m,s.length-m-p.length);rawY=clamp(rawY,m,s.width-m-p.width);
 let xs=[rawX,m,s.length-m-p.length],ys=[rawY,m,s.width-m-p.width];
 s.placed.filter(q=>q.id!==p.id).forEach(q=>{xs.push(q.x-p.length-k,q.x+q.length+k);ys.push(q.y-p.width-k,q.y+q.width+k)});
 xs=[...new Set(xs.filter(x=>x>=m-.01&&x+p.length<=s.length-m+.01))];
 ys=[...new Set(ys.filter(y=>y>=m-.01&&y+p.width<=s.width-m+.01))];
 let candidates=[];
 for(const x of xs)for(const y of ys){let snapped=Math.abs(x-rawX)<=threshold||Math.abs(y-rawY)<=threshold||x===rawX&&y===rawY;if(snapped&&objectCanDrop(s,p,x,y))candidates.push({x,y,d:Math.hypot(x-rawX,y-rawY)})}
 if(!candidates.length)for(const x of xs)for(const y of ys)if(objectCanDrop(s,p,x,y))candidates.push({x,y,d:Math.hypot(x-rawX,y-rawY)+threshold*10});
 return candidates.sort((a,b)=>a.d-b.d)[0]||null;
}
function previewRectangle(sheetEl,s,rect,label){let t=sheetIsTransposed(s),d=document.createElement('div'),left=t?rect.y/s.width:rect.x/s.length,top=t?(s.length-rect.x-rect.width)/s.length:rect.y/s.width,width=t?rect.height/s.width:rect.width/s.length,height=t?rect.width/s.length:rect.height/s.width,horizontal=t?rect.height:rect.width,vertical=t?rect.width:rect.height;d.className=`placementPreview ${label==='Свободный остаток'?'freeRemainderPreview':''}`;d.innerHTML=`<span>${label}</span><b>${Math.round(horizontal)}</b><i>${Math.round(vertical)}</i>`;d.style.left=left*100+'%';d.style.top=top*100+'%';d.style.width=width*100+'%';d.style.height=height*100+'%';d.title=`${label}: ${Math.round(rect.width)} × ${Math.round(rect.height)} мм`;sheetEl.append(d);return d}
function freeRectangleAt(sheetEl,s,e){let m=Math.max(0,+$('#margin').value||0),k=Math.max(0,+$('#kerf').value||0),sr=sheetEl.getBoundingClientRect(),point=sheetClickPoint(s,sheetEl,e),px=point.x,py=point.y,left=m,top=m,right=s.length-m,bottom=s.width-m;if(right<=left||bottom<=top||px<left||px>right||py<top||py>bottom)return null;let blocked=s.placed.map(q=>({left:Math.max(left,q.x-k),top:Math.max(top,q.y-k),right:Math.min(right,q.x+q.length+k),bottom:Math.min(bottom,q.y+q.width+k)})).filter(q=>q.right>q.left&&q.bottom>q.top),xs=[left,right],ys=[top,bottom];blocked.forEach(q=>{xs.push(q.left,q.right);ys.push(q.top,q.bottom)});xs=[...new Set(xs)].sort((a,b)=>a-b);ys=[...new Set(ys)].sort((a,b)=>a-b);let best=null,contains=(a,b,c,d)=>a<=px+0.001&&c>=px-0.001&&b<=py+0.001&&d>=py-0.001,free=(a,b,c,d)=>!blocked.some(q=>a<q.right-0.001&&c>q.left+0.001&&b<q.bottom-0.001&&d>q.top+0.001);for(const x0 of xs)for(const x1 of xs)if(x1>x0&&x0>=left&&x1<=right&&contains(x0,top,x1,bottom))for(const y0 of ys)for(const y1 of ys)if(y1>y0&&y0>=top&&y1<=bottom&&contains(x0,y0,x1,y1)&&free(x0,y0,x1,y1)){let area=(x1-x0)*(y1-y0);if(!best||area>best.width*best.height)best={x:x0,y:y0,width:x1-x0,height:y1-y0}}return best}
function clearPlacementPreview(){document.querySelectorAll('.placementPreview').forEach(x=>x.remove());placementCandidate=null;placementSelection=null}
function showPieceNotice(anchor,message){clearTimeout(pieceNoticeTimer);document.querySelectorAll('.pieceNotice').forEach(x=>x.remove());if(!anchor)return;let notice=document.createElement('div');notice.className='pieceNotice';notice.textContent=message;document.body.append(notice);let r=anchor.getBoundingClientRect(),gap=8,left=Math.min(Math.max(8,r.left),Math.max(8,window.innerWidth-notice.offsetWidth-8)),top=r.bottom+gap;if(top+notice.offsetHeight>window.innerHeight)top=Math.max(8,r.top-notice.offsetHeight-gap);notice.style.left=left+'px';notice.style.top=top+'px';pieceNoticeTimer=setTimeout(()=>{notice.remove()},4500)}
function commitPlacementCandidate(sheet){let c=placementCandidate;if(!c||c.sheet!==sheet||!bestResult)return false;let source=bestResult.unplaced.find(q=>q.id===c.p.id);if(!source){clearPlacementPreview();return false}let placed={...source,length:c.p.length,width:c.p.width,x:c.pos.x,y:c.pos.y};if(source.length!==c.p.length||source.width!==c.p.width)placed.rotation=source.rotation===90?0:90;sheet.placed.push(placed);bestResult.unplaced=bestResult.unplaced.filter(q=>q.id!==source.id);bestResult.manual=true;layouts=bestResult.all.filter(s=>s.placed.length);bestResult.layouts=layouts;clearPlacementPreview();render(bestResult.all,bestResult.unplaced);status.textContent=`Деталь «${source.name}» установлена в выбранное место.`;return true}
function showPlacementPreview(sheetEl,s,e){clearPlacementPreview();if(!bestResult)return;if(!bestResult.unplaced.length){let rest=freeRectangleAt(sheetEl,s,e);if(rest){let element=previewRectangle(sheetEl,s,rest,'Свободный остаток');placementSelection={sheet:s,element,kind:'remainder'}}return}let point=sheetClickPoint(s,sheetEl,e),candidates=[];bestResult.unplaced.slice().sort((a,b)=>b.length*b.width-a.length*a.width).forEach(p=>{let vs=p.rotate&&p.length!==p.width?[p,{...p,length:p.width,width:p.length}]:[p];vs.forEach(v=>{let rawX=point.x-v.length/2,rawY=point.y-v.width/2,pos=snapPlacement(s,v,rawX,rawY,sheetEl);if(pos)candidates.push({p:v,pos,dist:Math.hypot(pos.x-rawX,pos.y-rawY)})})});let best=candidates.sort((a,b)=>a.dist-b.dist)[0];if(!best)return;placementCandidate={sheet:s,p:best.p,pos:best.pos};let element=previewRectangle(sheetEl,s,{x:best.pos.x,y:best.pos.y,width:best.p.length,height:best.p.width},best.p.name);placementSelection={sheet:s,element,kind:'placement'}}
function pointInElement(element,e){if(!element)return false;let r=element.getBoundingClientRect();return e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom}
document.addEventListener('click',e=>{let sheet=e.target.closest?.('.sheet');if(sheet&&e.target===sheet){let s=allSheetByIndex(sheet.dataset.sheetIndex);if(!s)return;if(placementSelection?.sheet===s){if(placementSelection.kind==='placement'&&pointInElement(placementSelection.element,e)&&commitPlacementCandidate(s))return;clearPlacementPreview();return}if(placementSelection)clearPlacementPreview();showPlacementPreview(sheet,s,e)}else if(!e.target.closest?.('.placementPreview'))clearPlacementPreview()});
function rotateGroupPieces(p,anchor){let key=String(p.rotateGroup||'').trim(),placed=bestResult.all.flatMap(s=>s.placed),members=key?[...placed,...bestResult.unplaced].filter(q=>String(q.rotateGroup||'').trim()===key):[p];const reject=message=>{status.textContent=message;showPieceNotice(anchor,message)};const subject=key?`Группу «${key}»`:`Деталь «${p.name}»`;if(key&&members.some(q=>q.rotate===false)){return reject(`Группу «${key}» нельзя повернуть: у одной из деталей поворот запрещён.`)}let plans=[],bySheet=new Map(),kerf=Math.max(0,+$('#kerf').value||0),margin=Math.max(0,+$('#margin').value||0),fitsMaterial=(q,l,w)=>bestResult.all.some(s=>s.material===q.material&&l+2*margin<=s.length&&w+2*margin<=s.width);for(const q of members){let sheet=bestResult.all.find(x=>x.placed.some(z=>z===q||z.id===q.id)),length=q.width,width=q.length,x=(q.x||0)+(q.length-length)/2,y=(q.y||0)+(q.width-width)/2,rotation=q.rotation===90?0:90;if(!fitsMaterial(q,length,width)){return reject(`${subject} нельзя повернуть: деталь «${q.name}» (${length} × ${width} мм) не помещается ни в один материал.`)}if(sheet){let test={...sheet,placed:sheet.placed.filter(z=>!members.some(m=>m===z||m.id===z.id))},rotated={...q,length,width},originX=x,originY=y,sheetEl=document.querySelector(`.sheet[data-sheet-index="${bestResult.all.indexOf(sheet)}"]`),position=sheetEl?snapPlacement(test,rotated,originX,originY,sheetEl):null;if(position){x=position.x;y=position.y}else{x=Math.max(margin,Math.min(sheet.length-margin-length,originX));y=Math.max(margin,Math.min(sheet.width-margin-width,originY));if(!objectCanDrop(test,rotated,x,y)){return reject(`${subject} нельзя повернуть: не хватает свободного места.`)}}if(!bySheet.has(sheet))bySheet.set(sheet,[]);bySheet.get(sheet).push({...q,length,width,x,y})}plans.push({q,length,width,x,y,rotation})}for(const group of bySheet.values())for(let i=0;i<group.length;i++)for(let j=i+1;j<group.length;j++){let a=group[i],b=group[j];if(a.x<b.x+b.length+kerf&&a.x+a.length+kerf>b.x&&a.y<b.y+b.width+kerf&&a.y+a.width+kerf>b.y){return reject(`${subject} нельзя повернуть: детали пересекаются.`)}}plans.forEach(v=>Object.assign(v.q,{length:v.length,width:v.width,x:v.x,y:v.y,rotation:v.rotation}));bestResult.manual=true;layouts=bestResult.all.filter(s=>s.placed.length);bestResult.layouts=layouts;render(bestResult.all,bestResult.unplaced);status.textContent=key?`Группа «${key}» повернута на 90°.`:`Деталь «${p.name}» повернута на 90°.`}
function pieceElement(p,containerW,containerH,source,transposed=false){
 let d=document.createElement('div');d.className=`piece ${source==='unplaced'?'unplacedPiece':'placedPiece'}`;pieceLabels(d,p,source,transposed);d.title=`${p.name}: ${p.length} × ${p.width} мм`;d.dataset.pieceId=p.id||'';d.dataset.transposed=transposed?'1':'0';if(transposed){d.style.left=(p.y||0)/containerH*100+'%';d.style.top=(containerW-(p.x||0)-p.length)/containerW*100+'%';d.style.width=p.width/containerH*100+'%';d.style.height=p.length/containerW*100+'%'}else{d.style.left=(p.x||0)/containerW*100+'%';d.style.top=(p.y||0)/containerH*100+'%';d.style.width=p.length/containerW*100+'%';d.style.height=p.width/containerH*100+'%'}
 d.addEventListener('contextmenu',e=>{e.preventDefault();e.stopPropagation();clearPlacementPreview();rotateGroupPieces(p,d)});
 d.addEventListener('pointerdown',e=>{if(e.button!==0||!bestResult)return;e.preventDefault();activeDragCancel?.();document.querySelectorAll('.dragGhost').forEach(x=>x.remove());let rect=d.getBoundingClientRect(),dx=e.clientX-rect.left,dy=e.clientY-rect.top,sourceSheet=source==='sheet'?bestResult.all.find(s=>s.placed.some(q=>q===p||q.id===p.id)):null,preview=sourceSheet?{s:sourceSheet,pos:{x:p.x,y:p.y}}:null,ghost=d.cloneNode(true);ghost.classList.add('dragGhost');Object.assign(ghost.style,{position:'fixed',left:rect.left+'px',top:rect.top+'px',width:rect.width+'px',height:rect.height+'px',zIndex:10000,pointerEvents:'none'});document.body.append(ghost);d.style.visibility='hidden';
  d.style.display='none';let active=true;const cleanup=()=>{document.removeEventListener('pointermove',move);document.removeEventListener('pointerup',finish);document.removeEventListener('pointercancel',cancel);document.removeEventListener('visibilitychange',cancel);window.removeEventListener('blur',cancel);window.removeEventListener('scroll',cancel,true);window.removeEventListener('wheel',cancel,true);if(activeDragCancel===cancel)activeDragCancel=null};const cancel=()=>{if(!active)return;active=false;cleanup();ghost.remove();d.style.visibility='';d.style.display=''};activeDragCancel=cancel;const move=q=>{let hit=document.elementFromPoint(q.clientX,q.clientY),sheetEl=hit?.closest('.sheet');if(sheetEl){let s=allSheetByIndex(sheetEl.dataset.sheetIndex),sr=sheetEl.getBoundingClientRect(),point=sheetPointAt(s,sheetEl,q.clientX-dx,q.clientY-dy,p),pos=snapPlacement(s,p,point.x,point.y,sheetEl);if(pos){preview={s,pos};setGhostOnSheet(ghost,s,sr,pos,p)}return}ghost.style.width=rect.width+'px';ghost.style.height=rect.height+'px';ghost.style.left=q.clientX-dx+'px';ghost.style.top=q.clientY-dy+'px'};
  const finish=q=>{if(!active)return;active=false;cleanup();let hit=q&&document.elementFromPoint(q.clientX,q.clientY),sheetEl=hit?.closest('.sheet'),freeEl=hit?.closest('#unplaced'),moved=false;
   if(sheetEl){let s=allSheetByIndex(sheetEl.dataset.sheetIndex),sr=sheetEl.getBoundingClientRect(),point=sheetPointAt(s,sheetEl,q.clientX-dx,q.clientY-dy,p),pos=preview&&preview.s===s?preview.pos:snapPlacement(s,p,point.x,point.y,sheetEl);if(pos){if(sourceSheet)removePiece(sourceSheet.placed,p);else removePiece(bestResult.unplaced,p);s.placed.push({...p,x:pos.x,y:pos.y});moved=true;status.textContent=`Деталь «${p.name}» размещена с привязкой к ближайшей границе.`}else status.textContent='Для детали нет допустимой позиции без наложения.'}
   else if(freeEl){let board=$('#unplacedBoard'),br=board.getBoundingClientRect(),ref=layouts[0]||bestResult.all[0],scale=ref?(document.querySelector('.sheet')?.getBoundingClientRect().width||306)/(sheetIsTransposed(ref)?ref.width:ref.length):.2,x=Math.max(0,(q.clientX-dx-br.left)/scale),y=Math.max(0,(q.clientY-dy-br.top)/scale);if(sourceSheet){removePiece(sourceSheet.placed,p);bestResult.unplaced.push({...p,x,y});status.textContent=`Деталь «${p.name}» снята с материала.`}else{p.x=x;p.y=y;status.textContent=`Позиция детали «${p.name}» изменена.`}moved=true}
   ghost.remove();d.style.visibility='';d.style.display='';if(moved){bestResult.manual=true;layouts=bestResult.all.filter(s=>s.placed.length);bestResult.layouts=layouts}render(bestResult.all,bestResult.unplaced)};
  document.addEventListener('pointermove',move);document.addEventListener('pointerup',finish);document.addEventListener('pointercancel',cancel);document.addEventListener('visibilitychange',cancel);window.addEventListener('blur',cancel);window.addEventListener('scroll',cancel,true);window.addEventListener('wheel',cancel,true)
 });return d;
}
function render(all,un){let area=all.reduce((n,s)=>n+s.length*s.width,0),used=all.reduce((n,s)=>n+s.placed.reduce((a,p)=>a+p.length*p.width,0),0);$('#stats').textContent=`Листов: ${layouts.length} · Деталей: ${all.reduce((n,s)=>n+s.placed.length,0)} · Не размещено: ${un.length} · Использование: ${area?Math.round(used/area*100):0}%`;$('#unplaced').classList.remove('hidden');$('#layouts').innerHTML='';layouts.forEach((s,i)=>{let transposed=sheetIsTransposed(s),box=document.createElement('div');box.className='layout';box.innerHTML=`<h3>Лист ${i+1}: ${s.material} (${s.length} × ${s.width} мм)</h3><div class="sheet" style="width:100%;aspect-ratio:${transposed?s.width:s.length}/${transposed?s.length:s.width}"></div>`;let el=box.querySelector('.sheet');el.dataset.transposed=transposed?'1':'0';enableSheetDrop(el,s);s.placed.forEach(p=>el.append(pieceElement(p,s.length,s.width,'sheet',transposed)));$('#layouts').append(box)});let board=$('#unplacedBoard');board.innerHTML='';if(un.length){board.className='unplacedBoard';let gap=+$('#kerf').value||0,ref=layouts[0]||all[0],scale=ref?((document.querySelector('.sheet')?.getBoundingClientRect().width||306)/(sheetIsTransposed(ref)?ref.width:ref.length)):.2,visibleW=Math.max(300,board.parentElement.clientWidth||400),visibleH=Math.max(700,$('#layouts').getBoundingClientRect().height||700),bw=Math.max(visibleW/scale,1600,...un.map(p=>(p.x||0)+p.length)),bh=Math.max(visibleH/scale,1000,...un.map(p=>(p.y||0)+p.width));let x=0,y=0,rowH=0;un.forEach(p=>{if(!Number.isFinite(p.x)||!Number.isFinite(p.y)){if(x+p.length>bw){x=0;y+=rowH+gap;rowH=0}p.x=x;p.y=y;x+=p.length+gap;rowH=Math.max(rowH,p.width)}else{bw=Math.max(bw,p.x+p.length);bh=Math.max(bh,p.y+p.width)}});board.style.aspectRatio='auto';board.style.width=Math.max(visibleW,bw*scale)+'px';board.style.height=Math.max(visibleH,bh*scale)+'px';un.forEach(p=>board.append(pieceElement(p,bw,bh,'unplaced')))}else{board.className='unplacedBoard emptyUnplaced';board.style.aspectRatio='auto';board.style.width='100%';board.style.height='100px';board.innerHTML='<span>Все детали размещены</span>'}$('#unplacedList').innerHTML=un.length?`<table class="unplacedTable"><thead><tr><th>№</th><th>Наименование</th><th>Материал</th><th>Длина</th><th>Ширина</th><th>Кол-во</th></tr></thead><tbody>${un.map((x,i)=>`<tr><td>${i+1}</td><td>${x.name}</td><td>${x.material}</td><td>${x.length}</td><td>${x.width}</td><td>1</td></tr>`).join('')}</tbody></table>`:''}
$('#calcBtn').onclick=()=>calculate();document.addEventListener('keydown',e=>{if(e.key==='F9'){e.preventDefault();calculate()}});$('#exportBtn').onclick=()=>{let csv='Наименование;Материал;Длина;Ширина;Кол-во;Поворот;Группа поворота\n';layouts.forEach(s=>s.placed.forEach(p=>csv+=`${p.name};${s.material};${p.length};${p.width};1;${p.rotate?'Да':'Нет'};${p.rotateGroup||''}\n`));let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([ '\ufeff'+csv],{type:'text/csv'}));a.download='cutting-details.csv';a.click()};
$('#csv').onchange=e=>{let f=e.target.files[0];if(!f)return;let clear=window.confirm('Очистить текущий список деталей перед импортом?\n\n«ОК» — очистить и загрузить CSV.\n«Отмена» — добавить детали к текущему списку.');if(clear)tbody('parts').innerHTML='';let r=new FileReader;r.onload=()=>{let lines=r.result.replace(/^\ufeff/,'').trim().split(/\r?\n/).filter(Boolean),header=(lines.shift()||'').split(/[;,]/).map(x=>x.trim().toLowerCase()),isResult=header.includes('лист')&&header.includes('деталь'),isNumbered=header.includes('№');lines.forEach(line=>{let v=line.split(/[;,]/).map(x=>x.trim()),name,material,length,width,qty,rotate,rotateGroup;if(isResult){[,material,name,length,width,rotate,rotateGroup]=v;qty=1}else if(isNumbered){[,name,material,length,width,qty,rotate,rotateGroup]=v}else{[name,material,length,width,qty,rotate,rotateGroup]=v}tbody('parts').append(row('part',{name,material,length,width,qty:qty||1,rotate:rotate!=='Нет',rotateGroup}))});sync()};r.readAsText(f,'UTF-8')};
try{load(JSON.parse(localStorage.cutMvp))}catch{load({})}
