(function(){
  const key='cuttingProjects', panel=document.querySelector('#projectsPanel');
  if(!panel)return;
  const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const read=()=>{try{return JSON.parse(localStorage.getItem(key)||'[]')}catch{return[]}};
  let projects=read().map(p=>({...p,status:['draft','working','calculated','done','archived'].includes(p.status)?p.status:'draft'})), activeId=null, emptyGroups=1, pickerGroup=0;
  const statusNames={draft:'Черновик',working:'В работе',calculated:'Рассчитан',done:'Завершён',archived:'Архив'};
  const statusClass=s=>s==='calculated'?'calculated':s==='working'?'working':s==='done'?'done':s==='archived'?'archived':'draft';
  const db=()=>window.materialDbState?.db||{sheets:[],edges:[]};
  const unique=a=>[...new Set(a.filter(Boolean))].sort((x,y)=>String(x).localeCompare(String(y),'ru'));
  const materialRecords=()=>db().sheets.filter(x=>x.name);
  const edgeRecords=()=>db().edges.filter(x=>x.name);
  const nameOf=x=>typeof x==='string'?x:x?.name;
  const materialRecord=name=>materialRecords().find(item=>item.name===name||item.shortName===name)||{};
  const displayName=x=>{const name=nameOf(x),record=typeof x==='object'&&x?x:materialRecord(name);return String(record?.shortName||name||'')};
  const active=()=>projects.find(x=>x.id===activeId);
  const persist=()=>localStorage.setItem(key,JSON.stringify(projects));
  const materialNames=()=>unique(materialRecords().map(x=>x.name));
  const edgeNames=()=>unique(edgeRecords().map(x=>x.name));
  const baseNames=()=>unique(['ДСП','Фасадный материал','ХДФ','Кромка',...materialRecords().flatMap(x=>[x.group,x.subgroup])]);
  function projectMaterialNames(){return unique(active()?.materials?.map(nameOf)||[])}
  function projectEdgeNames(){return unique(active()?.edges?.map(nameOf)||[])}
  function materialMeta(name){const record=materialRecord(name);const size=record.length&&record.width?`${record.length}×${record.width}${record.thickness?`×${record.thickness}`:''} мм`:'';return {record,subtitle:[size,record.supplier||record.brand].filter(Boolean).join(', ')}}
  function normalizeProject(p){p.materials=Array.isArray(p.materials)?p.materials.map(x=>{if(typeof x==='string')return {name:x};return {...x,name:nameOf(x)} }).filter(x=>x.name):[];p.edges=Array.isArray(p.edges)?p.edges.map(nameOf).filter(Boolean):[];p.bases=Array.isArray(p.bases)?p.bases:[];p.status=statusNames[p.status]?p.status:'draft';p.note=String(p.note||'');return p}
  function syncProjectSheets(){const current=active();if(!current)return;const list=(current.materials||[]).map(x=>{const record=materialRecord(nameOf(x));return {material:nameOf(x),length:Number(x.length)||Number(record.length)||2800,width:Number(x.width)||Number(record.width)||2070,qty:Number(x.qty)||1}});const sheetBody=tbody('sheets');if(!sheetBody||typeof row!=='function'||typeof sync!=='function')return;sheetBody.innerHTML='';list.forEach(x=>sheetBody.append(row('sheet',x)));sync(false);refreshMaterialControls?.();requestAnimationFrame(()=>typeof renderDraftPreview==='function'&&renderDraftPreview())}
  function fillMaterialPick(){const search=String($('#projectMaterialSearch')?.value||'').trim().toLocaleLowerCase('ru');const used=new Set(projectMaterialNames());const items=materialRecords().filter(x=>!used.has(x.name)&&[x.name,x.shortName,x.supplier,x.article].some(v=>String(v||'').toLocaleLowerCase('ru').includes(search)));$('#projectMaterialPick').innerHTML='<option value="">Добавить материал…</option>'+items.map(x=>`<option value="${esc(x.name)}">${esc(displayName(x))}</option>`).join('');$('#projectMaterialOptions').innerHTML=items.map(x=>`<button type="button" class="projectMaterialOption" data-material-value="${esc(x.name)}">${esc(displayName(x))}</button>`).join('')||'<span class="projectHint">Ничего не найдено.</span>'}
  function updateMaterialPicker(){const button=$('#projectMaterialPickButton');if(!button)return;const pending=$('#projectMaterialPick')?.value,name=pending||projectMaterialNames()[0],meta=name?materialMeta(name):{record:{},subtitle:''},image=meta.record.imageUrl?` style="background-image:url('${esc(meta.record.imageUrl)}')"`:'';button.innerHTML=name?`<span class="projectMaterialThumb${meta.record.imageUrl?'':' isEmpty'}"${image}></span><span class="projectMaterialInfo"><strong>${esc(displayName(meta.record||name))}</strong>${meta.subtitle?`<small>${esc(meta.subtitle)}</small>`:''}</span><span class="projectMaterialChevron">⌄</span>`:`<span class="projectMaterialThumb isEmpty"></span><span class="projectMaterialPlaceholder">Выберите материал…</span><span class="projectMaterialChevron">⌄</span>`}
  function renderCatalog(){
    const materialSet=new Set(projectMaterialNames()), edgeSet=new Set(projectEdgeNames());
    const names=projectMaterialNames(),groupCount=names.length+emptyGroups;$('#projectMaterials').innerHTML=Array.from({length:groupCount},(_,index)=>{const n=names[index]||'',item=n?(active()?.materials?.find(x=>nameOf(x)===n)||{}):{},meta=n?materialMeta(n):{record:{},subtitle:''},image=meta.record.imageUrl?` style="background-image:url('${esc(meta.record.imageUrl)}')"`:'',edgeOptions='<option value="">Добавить кромку…</option>'+edgeNames().map(edge=>`<option value="${esc(edge)}" ${String(item.edge||'')===edge?'selected':''}>${esc(edge)}</option>`).join(''),content=n?`<span class="projectMaterialThumb${meta.record.imageUrl?'':' isEmpty'}"${image}></span><span class="projectMaterialInfo"><strong>${esc(n)}</strong>${meta.subtitle?`<small>${esc(meta.subtitle)}</small>`:''}</span>`:'<span class="projectMaterialThumb isEmpty"></span><span class="projectMaterialInfo"><strong>Выберите материал…</strong><small>Материал не выбран</small></span>';return `<tr class="projectMaterialRow"><td colspan="2"><div class="projectMaterialCard projectGroupPicker projectMaterialPicker" role="button" tabindex="0" data-group-index="${index}">${content}<span class="projectMaterialChevron">⌄</span>${n?`<button type="button" class="projectRemove" data-remove-material="${esc(n)}">×</button>`:''}</div><div class="projectGroupFields"><label>Листов<input type="number" min="1" data-material-field="qty" data-material-name="${esc(n)}" value="${Number(item.qty)||1}"></label><label>Кромка<select data-material-field="edge" data-material-name="${esc(n)}">${edgeOptions}</select></label></div></td></tr>`}).join('');
    $('#projectEdges').innerHTML=projectEdgeNames().map(n=>`<tr><td>${esc(n)}</td><td><button type="button" class="projectRemove" data-remove-edge="${esc(n)}">×</button></td></tr>`).join('')||'<tr><td colspan="2" class="projectHint">Кромки проекта пока не добавлены.</td></tr>';
    fillMaterialPick();updateMaterialPicker();$('#addProjectMaterial').disabled=emptyGroups>0;const first=active()?.materials?.[0];$('#projectQty').value=Number(first?.qty)||1;
    $('#projectEdgePick').innerHTML='<option value="">Добавить кромку…</option>'+edgeNames().filter(n=>!edgeSet.has(n)).map(n=>`<option value="${esc(n)}">${esc(n)}</option>`).join('');
    syncProjectSheets();window.dispatchEvent(new CustomEvent('projectMaterialsChanged'));
  }
  function renderList(){const visible=projects.filter(p=>p.status!=='archived');$('#projectList').innerHTML=visible.length?visible.map(p=>`<div class="projectItem ${p.id===activeId?'active':''}" data-project-id="${p.id}"><button type="button" class="projectSelect"><strong>${esc(p.name)}</strong><small class="projectStatus ${statusClass(p.status)}">${statusNames[p.status]}</small></button><button type="button" class="projectDelete" title="Удалить проект" aria-label="Удалить проект">×</button></div>`).join(''):'<div class="projectHint">Сохранённых проектов пока нет.</div>'}
  function collect(){const name=$('#projectName').value.trim()||'Новый проект',old=active(),stored=read().find(x=>x.id===old?.id||x.name===name),baseMaterials=old?.materials?.length?old.materials:(stored?.materials||[]),domNames=[...document.querySelectorAll('#projectMaterials .projectMaterialCard')].map(card=>card.querySelector('[data-remove-material]')?.dataset.removeMaterial||'').filter(Boolean),materials=domNames.length?domNames.map(materialName=>{const item=baseMaterials.find(x=>(typeof x==='string'?x:x?.name)===materialName||materialRecord(typeof x==='string'?x:x?.name).shortName===materialName)||{},record=materialRecord(materialName);return {...item,name:materialName,length:Number(item.length)||Number(record.length)||2800,width:Number(item.width)||Number(record.width)||2070}}):baseMaterials,p=normalizeProject({id:activeId||`project-${Date.now().toString(36)}`,name,note:$('#projectNote')?.value||old?.note||stored?.note||'',materials,edges:old?.edges||stored?.edges||[],bases:[...document.querySelectorAll('[data-project-base]:checked')].map(x=>x.value),status:old?.status||stored?.status||'draft',updated:new Date().toISOString()});if(old)Object.assign(old,p);else projects.unshift(p);activeId=p.id;persist();renderList();return p}
function newProject(){activeId=null;emptyGroups=1;$('#projectName').value='';if($('#projectNote'))$('#projectNote').value='';if(typeof resetCurrentResult==='function')resetCurrentResult();if(typeof load==='function')load({sheets:[],parts:[]});window.restoreDetailsTables?.([{id:`details-${Date.now().toString(36)}`,name:'Список 1',material:'',parts:[]}]);if(typeof load==='function')load({sheets:[],parts:[]});localStorage.setItem('cutMvp',JSON.stringify({sheets:[],parts:[]}));document.querySelectorAll('[data-table-material]').forEach(select=>{select.value=''});renderCatalog();document.querySelector('#layouts')?.replaceChildren(Object.assign(document.createElement('div'),{className:'empty',textContent:'Добавьте материалы и детали для нового проекта'}));document.querySelector('#unplaced')?.classList.add('hidden');renderList();$('#projectName').focus()}
  function selectProject(id){const p=projects.find(x=>x.id===id);if(!p)return;normalizeProject(p);activeId=id;emptyGroups=p.materials.length?0:1;$('#projectName').value=p.name;if($('#projectNote'))$('#projectNote').value=p.note||'';renderCatalog();renderList();updateProjectStatus()}
  function updateProjectStatus(){const p=active(),badge=$('#projectStatus');if(!badge)return;badge.textContent=statusNames[p?.status||'draft'];badge.className=`projectStatus ${statusClass(p?.status)}`;$('#finishProjectBtn').textContent=p?.status==='done'?'Вернуть в работу':'Завершить';$('#archiveProjectBtn').textContent=p?.status==='archived'?'Восстановить':'В архив'}
  function setProjectStatus(status){const p=active();if(!p)return;p.status=status;p.updated=new Date().toISOString();persist();renderList();updateProjectStatus()}
  function addMaterial(name){if(!name)return;const p=collect(),record=materialRecord(name);if(!p.materials.some(x=>nameOf(x)===name))p.materials.push({name,length:Number(record.length)||2800,width:Number(record.width)||2070,qty:1});persist();renderCatalog()}
  function addEdge(name){if(!name)return;const p=collect();if(!p.edges.some(x=>nameOf(x)===name))p.edges.push(name);persist();renderCatalog()}
  function exportProject(){const p=collect();syncProjectSheets();let cuttingData=null;try{cuttingData=JSON.parse(localStorage.cutMvp||'null')}catch{}const sheets=Array.isArray(cuttingData?.sheets)?cuttingData.sheets:[],materials=(p.materials||[]).map(item=>{const sheet=sheets.find(x=>String(x.material||'')===String(nameOf(item)));return {...item,name:nameOf(item),qty:Number(item.qty)||Number(sheet?.qty)||1}});p.materials=materials;p.edges=[...(p.edges||[])];const exportSheets=sheets.length?sheets:materials.map(item=>({material:item.name,length:item.length,width:item.width,qty:item.qty}));const payload={format:'cutting-project',version:1,project:p,materials,materialDb:db(),cuttingData:{...(cuttingData||{}),sheets:exportSheets},detailsTables:window.getDetailsTablesSnapshot?.()||null};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));a.download=`${p.name.replace(/[\\/:*?"<>|]+/g,'_')||'project'}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),0)}
  function importProject(file){const r=new FileReader();r.onload=()=>{try{const data=JSON.parse(r.result),isCuttingJson=data.format==='cutting-json',cuttingData=isCuttingJson?{sheets:data.sheets||[],parts:data.parts||[]}:data.cuttingData,raw=data.project||(isCuttingJson?{name:String(file.name||'Импортированный проект').replace(/\.json$/i,''),materials:[],edges:[]}:data);if(!raw.name)throw Error('В файле нет проекта');if(data.materialDb?.sheets||data.materialDb?.edges){const target=db();for(const kind of ['sheets','edges'])for(const item of (data.materialDb[kind]||[])){if(!target[kind].some(x=>JSON.stringify(x)===JSON.stringify(item)))target[kind].push(item)}localStorage.setItem('cuttingMaterialDb',JSON.stringify(target))}const sourceMaterials=Array.isArray(raw.materials)&&raw.materials.length?raw.materials:(Array.isArray(data.materials)&&data.materials.length?data.materials:[]),sheets=Array.isArray(cuttingData?.sheets)?cuttingData.sheets:[],sheetByName=new Map(sheets.map(x=>[String(x.material||''),x])),materials=sourceMaterials.length?sourceMaterials.map(item=>{const material=typeof item==='string'?{name:item}:item||{},sheet=sheetByName.get(String(nameOf(material)||''));return {...material,name:nameOf(material),qty:Number(material.qty)||Number(sheet?.qty)||1}}):[...sheetByName.entries()].filter(([name])=>name).map(([name,sheet])=>({name,length:Number(sheet.length)||2800,width:Number(sheet.width)||2070,qty:Number(sheet.qty)||1}));const edges=Array.isArray(raw.edges)?raw.edges:(Array.isArray(data.edges)?data.edges:[]),p=normalizeProject({id:`project-${Date.now().toString(36)}`,name:String(raw.name),materials,edges,bases:raw.bases||[],updated:new Date().toISOString()});projects.unshift(p);activeId=p.id;persist();if(cuttingData&&typeof load==='function')load(cuttingData);window.restoreDetailsTables?.(data.detailsTables);$('#projectName').value=p.name;renderCatalog();renderList()}catch(e){alert('Не удалось открыть проект: '+e.message)}};r.readAsText(file,'UTF-8')}
  let preserveEmptyGroups=false;const originalRenderCatalog=renderCatalog;renderCatalog=()=>{if(!preserveEmptyGroups)emptyGroups=active()?.materials?.length?0:1;preserveEmptyGroups=false;originalRenderCatalog()};
  const style=document.createElement('style');style.textContent='#projectsPanel{width:100%!important;margin:0!important;border:0;border-bottom:1px solid #c7d0d3;border-radius:0;box-shadow:none;background:#f7f8f8;padding:0;overflow:visible}#projectsPanel .projectsHead{height:44px;padding:0 14px;background:#d5d7d8;display:flex;align-items:center;justify-content:space-between;color:#3d4a50;cursor:pointer}#projectsPanel .projectsHead h2{margin:0;font-size:14px;font-weight:600}#projectsPanel .projectsHead button{padding:3px 9px;background:transparent;color:#59676c}#projectsPanel .projectsContent{padding:10px 14px 14px;background:#fafafa}#projectsPanel.projectsCollapsed .projectsContent{display:none}.projectsToolbar,.projectsActions{display:flex;gap:6px;flex-wrap:wrap;margin-bottom:10px}.projectsToolbar button,.projectsActions button{padding:7px 9px;font-size:11px}.projectNameLabel{display:block;font-size:11px;color:#52636c}.projectNameLabel input{display:block;width:100%;margin-top:4px;padding:7px;border:1px solid #cbd6dc;border-radius:5px}.projectLists{display:grid;gap:8px;margin-top:10px}.projectLists fieldset{min-width:0;margin:0;padding:7px;border:1px solid #d4dde1}.projectLists legend{padding:0 4px;font-size:11px;color:#52636c}.projectCatalog{width:100%;border-collapse:collapse;font-size:11px;background:#fff}.projectCatalog th,.projectCatalog td{padding:5px 6px;border-bottom:1px solid #e1e7ea;text-align:left}.projectCatalog th{color:#60717a;background:#f0f4f6}.projectCatalog th:last-child,.projectCatalog td:last-child{width:28px}.projectAdd{display:flex;gap:5px;margin-bottom:6px}.projectAdd select{min-width:0;flex:1;padding:5px;border:1px solid #cbd6dc;border-radius:4px;font-size:11px}.projectAdd button{padding:5px 8px;font-size:11px}.projectRemove{padding:0 5px;background:transparent;color:#b42318;font-size:15px}.projectCheck{display:flex;align-items:flex-start;gap:6px;font-size:11px;color:#263943}.projectCheck input{margin:1px 0 0}.projectHint{font-size:11px;color:#809098}.projectList{display:grid;gap:3px}.projectItem{display:flex;align-items:center;border:1px solid #d6e0e4;background:#fff}.projectItem.active{border-color:#2c9c69;background:#eef7f2}.projectSelect{flex:1;padding:7px 8px;background:transparent;color:#263943;text-align:left;font-size:11px}.projectDelete{padding:4px 8px;background:transparent;color:#b42318;font-size:16px}#materialsPanel .materialDbToggle{display:flex!important}';document.head.append(style);
  document.head.append(Object.assign(document.createElement('style'),{textContent:'#materialsPanel{display:none!important}.projectSheetFields{display:flex;gap:5px;margin-top:5px}.projectSheetFields label{display:flex;align-items:center;gap:3px;color:#809098;font-size:10px}.projectSheetFields input{width:62px;padding:3px 4px;border:1px solid #cbd6dc;border-radius:3px;font-size:11px}.projectMaterialPicker{position:relative;min-width:0;flex:1}.projectMaterialPicker>button{width:100%;padding:5px 8px;border:1px solid #cbd6dc;border-radius:4px;background:#fff;color:#263943;text-align:left;font-size:11px}.projectMaterialMenu{position:absolute;z-index:20;top:100%;left:0;right:0;padding:5px;background:#fff;border:1px solid #9fb0b8;box-shadow:0 6px 16px #17334035}.projectMaterialMenu[hidden]{display:none}.projectMaterialSearch{width:100%;box-sizing:border-box;padding:5px;border:1px solid #cbd6dc;border-radius:4px;font-size:11px}.projectMaterialOptions{max-height:220px;overflow:auto;margin-top:4px}.projectMaterialOption{display:block;width:100%;padding:6px 7px;border:0;background:#fff;color:#263943;text-align:left;font-size:11px;cursor:pointer}.projectMaterialOption:hover{background:#edf5f7}'}));
  panel.querySelector('.projectsHead h2').textContent='Проект';
  const sectionNav=document.createElement('nav');sectionNav.className='projectSectionNav';sectionNav.setAttribute('aria-label','Разделы проекта');sectionNav.innerHTML='<div class="projectSectionNavTitle"><button type="button" class="projectSectionNavAdd" aria-label="Новый проект" title="Новый проект">＋</button><span class="projectSectionNavDivider" aria-hidden="true"></span><strong>Проекты</strong></div><button type="button" class="projectSectionNavItem active" data-project-section="projectBasics"><span class="projectSectionIcon">▤</span><span><strong>Основные параметры</strong><small>Название и примечание</small></span></button><button type="button" class="projectSectionNavItem" data-project-section="projectMaterialsSection"><span class="projectSectionIcon">▧</span><span><strong>Материалы</strong><small>Листы и кромки</small></span></button><button type="button" class="projectSectionNavItem" data-project-section="projectSettingsSection"><span class="projectSectionIcon">⚙</span><span><strong>Параметры</strong><small>Пропил и отступ</small></span></button><button type="button" class="projectSectionNavItem" data-project-section="projectArchiveSection"><span class="projectSectionIcon">▣</span><span><strong>Архив проектов</strong><small>Сохранённые проекты</small></span></button>';
  queueMicrotask(()=>{panel.querySelector('.projectsHead h2').textContent='Проект';panel.querySelector('.projectPanelHeader strong')?.replaceChildren(document.createTextNode('Проект'));sectionNav.innerHTML=sectionNav.innerHTML.replace('projectArchiveSection','projectList');panel.querySelector('.projectsContent').prepend(sectionNav);
  panel.querySelector('.projectNameLabel')?.setAttribute('id','projectBasics');panel.querySelector('.projectMaterialsField')?.setAttribute('id','projectMaterialsSection');panel.querySelector('.projectCuttingOptions')?.setAttribute('id','projectSettingsSection');
  const markSection=section=>{sectionNav.querySelectorAll('.projectSectionNavItem').forEach(item=>item.classList.toggle('active',item.dataset.projectSection===section))};
  sectionNav.addEventListener('click',event=>{const button=event.target.closest('[data-project-section]');if(!button)return;const target=panel.querySelector(`#${button.dataset.projectSection}`);if(target){target.scrollIntoView({behavior:'smooth',block:'start'});markSection(button.dataset.projectSection)}});});
  panel.querySelector('.projectsContent').innerHTML='<label class="projectNameLabel">Наименование проекта<input id="projectName" type="text" placeholder="Например, Кухня Петровых"></label><div class="projectLists"><div class="projectMaterialsField"><label class="projectSectionLabel"><span>Материалы</span><button id="addProjectMaterial" class="projectMaterialAdd" type="button" title="Добавить материал" aria-label="Добавить материал">＋</button></label><select id="projectMaterialPick" hidden></select><button id="projectMaterialPickButton" type="button" hidden></button><div id="projectMaterialMenu" class="projectMaterialMenu" hidden><input id="projectMaterialSearch" class="projectMaterialSearch" type="search" placeholder="Поиск материала…" aria-label="Поиск материала"><div id="projectMaterialOptions" class="projectMaterialOptions"></div></div><table class="projectCatalog projectMaterialsCatalog"><tbody id="projectMaterials"></tbody></table></div><div class="projectQtyField"><label for="projectQty">Количество листов<input id="projectQty" type="number" min="1" value="1"></label></div><div class="projectEdgesField"><label class="projectSectionLabel" for="projectEdgePick">Кромки</label><div class="projectAdd"><select id="projectEdgePick"></select><button id="addProjectEdge" type="button">Добавить</button></div><table class="projectCatalog"><tbody id="projectEdges"></tbody></table></div></div><div class="projectCuttingOptions"><label>Ширина пропила (мм)<input id="projectKerf" type="number" min="0" step="0.1" value="4"></label><label>Отступ от края (мм)<input id="projectMargin" type="number" min="0" step="1" value="0"></label><label>Максимум деталей в группе<input id="projectMaxUnplacedGroupSize" type="number" min="1" step="1" value="10"></label><label>Направление текстуры<select id="projectTextureDirection"><option value="length">▣&nbsp; Вдоль длины</option><option value="width">▣&nbsp; Поперёк длины</option></select></label></div><button id="projectAddMaterialBottom" type="button" class="projectAddMaterialBottom">＋&nbsp; Добавить материал</button><div class="projectAdvanced"><button type="button" class="projectAdvancedToggle">⚙&nbsp; Дополнительные параметры</button><div class="projectAdvancedActions"><button id="saveProjectFileBtn" type="button" class="secondary">Сохранить проект в файл</button><input id="projectFile" type="file" accept=".json,application/json" hidden></div></div><div id="projectList" class="projectList" aria-label="Сохранённые проекты"></div>';
  const panelHeader=document.createElement('div');panelHeader.className='projectPanelHeader';panelHeader.innerHTML='<strong>Материалы и параметры</strong><button type="button" class="projectPanelToggle" aria-label="Свернуть панель">⌃</button>';const panelContent=panel.querySelector('.projectsContent');panel.querySelector('.projectsHead').style.display='none';panel.insertBefore(panelHeader,panelContent);const togglePanel=()=>{const collapsed=panelContent.style.display!=='none';panel.dataset.panelCollapsed=String(collapsed);panel.classList.toggle('projectPanelCollapsed',collapsed);panel.classList.toggle('projectsCollapsed',collapsed);panel.style.setProperty('display','flex','important');panel.style.setProperty('flex-direction','column','important');panel.style.setProperty('height',collapsed?'0px':'auto','important');panelContent.style.setProperty('display',collapsed?'none':'block','important');panelHeader.querySelector('.projectPanelToggle').textContent=collapsed?'⌄':'⌃'};panelHeader.querySelector('.projectPanelToggle').onclick=e=>{e.stopPropagation();togglePanel()};panelHeader.onclick=e=>{if(!e.target.closest('button'))togglePanel()};panel.addEventListener('click',e=>{if(e.target===panel&&e.offsetY<=52)togglePanel()});
  $('#saveProjectBtn')?.addEventListener('click',()=>{collect();renderCatalog()});$('#saveProjectFileBtn')?.addEventListener('click',exportProject);$('#openProjectBtn')?.addEventListener('click',()=>$('#projectFile')?.click());$('#projectFile')?.addEventListener('change',e=>{if(e.target.files[0])importProject(e.target.files[0]);e.target.value=''});$('#addProjectMaterial').onclick=()=>{addMaterial($('#projectMaterialPick').value);$('#projectMaterialPick').value=''};$('#addProjectEdge').onclick=()=>{addEdge($('#projectEdgePick').value);$('#projectEdgePick').value=''};$('#projectName').onchange=()=>{if(activeId)collect()};$('#projectMaterials').onclick=e=>{const b=e.target.closest('[data-remove-material]');if(!b)return;const p=collect();p.materials=p.materials.filter(x=>nameOf(x)!==b.dataset.removeMaterial);persist();renderCatalog()};$('#projectEdges').onclick=e=>{const b=e.target.closest('[data-remove-edge]');if(!b)return;const p=collect();p.edges=p.edges.filter(p=>nameOf(p)!==b.dataset.removeEdge);persist();renderCatalog()};$('#projectList').onclick=e=>{const item=e.target.closest('[data-project-id]');if(!item)return;if(e.target.closest('.projectDelete')){projects=projects.filter(p=>p.id!==item.dataset.projectId);if(activeId===item.dataset.projectId)newProject();else{persist();renderList()}return}selectProject(item.dataset.projectId)};
  panel.addEventListener('input',e=>{const input=e.target.closest('[data-material-field="qty"]');if(!input)return;const item=active()?.materials?.find(x=>nameOf(x)===input.dataset.materialName);if(!item)return;item.qty=Math.max(1,Number(input.value)||1);persist();syncProjectSheets()});$('#projectMaterialSearch').addEventListener('input',fillMaterialPick);$('#projectMaterialPickButton').onclick=()=>{$('#projectMaterialMenu').hidden=!$('#projectMaterialMenu').hidden;if(!$('#projectMaterialMenu').hidden){$('#projectMaterialSearch').focus();fillMaterialPick()}};$('#projectMaterialOptions').onclick=e=>{const option=e.target.closest('[data-material-value]');if(!option)return;$('#projectMaterialPick').value=option.dataset.materialValue;$('#projectMaterialMenu').hidden=true;updateMaterialPicker()};document.addEventListener('click',e=>{if($('#projectMaterialMenu')?._targetPicker?.closest?.('#projectMaterialsGrid'))return;if(e.target.closest('.projectMaterialGridCard'))return;if(!e.target.closest('.projectMaterialPicker'))$('#projectMaterialMenu').hidden=true});$('.projectAdvancedToggle').onclick=()=>$('.projectAdvanced').classList.toggle('open');
  const projectKerf=$('#projectKerf'),projectMargin=$('#projectMargin'),projectMaxUnplacedGroupSize=$('#projectMaxUnplacedGroupSize'),projectTextureDirection=$('#projectTextureDirection');projectKerf.value=$('#kerf')?.value||4;projectMargin.value=$('#margin')?.value||10;projectKerf.step='0.5';projectMargin.step='1';projectKerf.min='0';projectMargin.min='0';projectMargin.value=projectMargin.value||10;projectKerf.addEventListener('input',e=>{$('#kerf').value=e.target.value;window.offerRecalcPrompt?.()});projectMargin.addEventListener('input',e=>{$('#margin').value=e.target.value;window.offerRecalcPrompt?.()});projectMaxUnplacedGroupSize.value=$('#projectMaxUnplacedGroupSize')?.value||10;projectTextureDirection.value=localStorage.getItem('cuttingTextureDirection')||'length';projectMaxUnplacedGroupSize.addEventListener('input',e=>{const value=Math.max(1,Math.floor(Number(e.target.value)||10));e.target.value=value;window.offerRecalcPrompt?.()});projectTextureDirection.addEventListener('change',e=>localStorage.setItem('cuttingTextureDirection',e.target.value));$('#projectAddMaterialBottom').onclick=()=>$('#addProjectMaterial').click();
  $('#projectQty').addEventListener('input',e=>{const item=active()?.materials?.[0];if(!item)return;item.qty=Math.max(1,Number(e.target.value)||1);persist();syncProjectSheets()});
  $('#projectMaterials').addEventListener('change',e=>{const select=e.target.closest('[data-material-field="edge"]');if(!select)return;const item=active()?.materials?.find(x=>nameOf(x)===select.dataset.materialName);if(!item)return;item.edge=select.value||'';if(item.edge&&!active().edges.includes(item.edge))active().edges.push(item.edge);persist();renderCatalog()});
  $('#projectMaterials').onclick=null;$('#projectMaterials').addEventListener('click',e=>{const button=e.target.closest('[data-remove-material]');if(!button)return;e.preventDefault();e.stopPropagation();const row=button.closest('.projectMaterialRow'),cell=row?.querySelector('td');if(!row||!cell||cell.querySelector('.projectRemoveConfirm'))return;const confirm=document.createElement('div');confirm.className='projectRemoveConfirm';const text=document.createElement('span');text.textContent=`Удалить материал «${button.dataset.removeMaterial}»?`;const yes=document.createElement('button');yes.type='button';yes.textContent='Удалить';const no=document.createElement('button');no.type='button';no.className='secondary';no.textContent='Отмена';confirm.append(text,yes,no);cell.prepend(confirm);no.onclick=()=>confirm.remove();yes.onclick=()=>{const project=active();if(!project)return;project.materials=project.materials.filter(item=>nameOf(item)!==button.dataset.removeMaterial);if(!project.materials.length)emptyGroups=1;persist();renderCatalog()}});
  $('#projectMaterials').addEventListener('click',e=>{const picker=e.target.closest('[data-group-index]');if(!picker)return;pickerGroup=Number(picker.dataset.groupIndex);$('#projectMaterialMenu').hidden=false;$('#projectMaterialSearch').focus();fillMaterialPick()});$('#addProjectMaterial').onclick=()=>{if(emptyGroups>0)return;emptyGroups++;renderCatalog()};$('#projectMaterialOptions').addEventListener('click',e=>{const option=e.target.closest('[data-material-value]');if(!option)return;const p=collect(),record=materialRecords().find(x=>x.name===option.dataset.materialValue)||{},index=pickerGroup;if(!p.materials[index])p.materials.push({name:option.dataset.materialValue,length:Number(record.length)||2800,width:Number(record.width)||2070,qty:1});else p.materials[index].name=option.dataset.materialValue;emptyGroups=Math.max(0,emptyGroups-1);$('#projectMaterialMenu').hidden=true;persist();renderCatalog()});
  const toggle=()=>{panel.classList.toggle('projectsCollapsed');$('#projectsToggle').textContent=panel.classList.contains('projectsCollapsed')?'⌄':'⌃'};$('#projectsToggle').onclick=e=>{e.stopPropagation();toggle()};panel.querySelector('.projectsHead').onclick=e=>{if(!e.target.closest('button'))toggle()};const materialsSectionToggle=panel.querySelector('.projectMaterialsField .projectSectionLabel');materialsSectionToggle?.addEventListener('click',e=>{if(e.target.closest('button'))return;materialsSectionToggle.parentElement.classList.toggle('projectMaterialsCollapsed')});
  const sidebar=$('#sidebarRoot'),materialPanel=$('#materialsPanel');if(sidebar){sidebar.prepend(panelHeader);sidebar.insertBefore(panel,sidebar.children[1]||null);const sectionTitle=sectionNav.querySelector('.projectSectionNavTitle'),oldTitle=panelHeader.querySelector('strong');if(sectionTitle&&oldTitle)oldTitle.replaceWith(sectionTitle);const resetSidebarScroll=()=>{sidebar.scrollTop=0};resetSidebarScroll();requestAnimationFrame(resetSidebarScroll);window.addEventListener('load',resetSidebarScroll,{once:true});window.addEventListener('pageshow',resetSidebarScroll);setTimeout(resetSidebarScroll,100)}else if(materialPanel)materialPanel.parentNode.insertBefore(panel,materialPanel);
  const topbar=document.createElement('div');topbar.id='projectTopbar';topbar.innerHTML='<span class="projectTopbarIcon" aria-hidden="true">▱</span><div class="projectTopbarMeta"><strong>Кухня Петровых</strong><span>ЛДСП Мадейвиль розовый&nbsp;&nbsp;•&nbsp;&nbsp;2 материала&nbsp;&nbsp;•&nbsp;&nbsp;13 деталей&nbsp;&nbsp;•&nbsp;&nbsp;Сохранено 2 минуты назад&nbsp;&nbsp;●</span></div><div class="projectTopbarActions"><button id="topbarImportBtn" type="button" class="secondary">⇧&nbsp; Импорт</button><button id="topbarAddPartBtn" type="button" class="secondary">＋&nbsp; Добавить детали</button><button id="topbarCalcBtn" type="button" class="primary">▶&nbsp; Рассчитать раскрой</button><button id="topbarPdfBtn" type="button" class="secondary">▣&nbsp; PDF</button><button id="topbarDxfBtn" type="button" class="secondary">▣&nbsp; DXF</button><button id="topbarMenuBtn" type="button" class="secondary" aria-label="Дополнительные действия">•••</button></div>';
  if(sidebar){sidebar.parentNode.insertBefore(topbar,sidebar);topbar.style.setProperty('top','8px','important');sidebar.style.setProperty('top','78px','important')}const resultPanel=document.querySelector('main>.result');resultPanel?.style.setProperty('top','78px','important');
  const topbarStyle=document.createElement('style');topbarStyle.textContent='#projectTopbar{position:absolute!important;left:0!important;right:0!important;top:0!important;height:62px!important;z-index:20!important;display:flex!important;align-items:center!important;gap:12px!important;padding:0 16px 0 24px!important;box-sizing:border-box;background:#051a27!important;border-bottom:1px solid rgba(91,151,180,.18)!important;box-shadow:none!important;color:#eaf5fb!important}#projectTopbar .projectTopbarIcon{display:grid;place-items:center;flex:0 0 38px;width:38px;height:38px;border:1px solid #1c5a7b;border-radius:6px;background:#0b2637;color:#e9f8ff;font-size:20px;line-height:1}#projectTopbar .projectTopbarMeta{display:flex;flex-direction:column;justify-content:center;gap:4px;min-width:245px;margin-right:auto;white-space:nowrap}#projectTopbar .projectTopbarMeta strong{color:#f3f8fb;font-size:16px;line-height:1.05}#projectTopbar .projectTopbarMeta span{color:#8faebb;font-size:11px;line-height:1.1}#projectTopbar .projectTopbarMeta span::first-letter{color:#4ed38a}#projectTopbar .projectTopbarActions{display:flex;align-items:center;gap:6px;margin-left:auto;white-space:nowrap}#projectTopbar .projectTopbarActions button{height:36px;padding:0 12px;border:1px solid rgba(73,133,162,.46);border-radius:5px;background:#0a2231;color:#dcecf3;font-size:12px;font-weight:600;box-shadow:none;cursor:pointer}#projectTopbar .projectTopbarActions button:hover{border-color:#31c8ff;background:#123b54}#projectTopbar .projectTopbarActions .primary{min-width:190px;border-color:#ff9a2f;background:#ff922c;color:#081620}#projectTopbar .projectTopbarActions .primary:hover{background:#ffa54a}#projectTopbar .projectTopbarActions #topbarMenuBtn{width:40px;padding:0;font-size:16px;letter-spacing:2px}@media(max-width:1250px){#projectTopbar .projectTopbarActions button{padding:0 9px;font-size:11px}#projectTopbar #topbarAddMaterialBtn{display:none}#projectTopbar .projectTopbarMeta{min-width:210px}#projectTopbar .projectTopbarMeta span{max-width:280px;overflow:hidden;text-overflow:ellipsis}}main>#sidebarRoot{top:70px!important}main>.result{top:62px!important}@media(max-width:900px){#projectTopbar{position:relative!important;left:auto!important;right:auto!important;top:auto!important;height:62px!important;padding:0 12px!important}main>#sidebarRoot{position:relative!important;top:auto!important;bottom:auto!important;width:100%!important;max-height:none!important}main>.result{position:relative!important;top:auto!important;left:auto!important;right:auto!important;min-height:70vh!important}#projectTopbar .projectTopbarMeta{min-width:0!important}#projectTopbar .projectTopbarMeta span{display:none!important}#projectTopbar #topbarAddPartBtn,#projectTopbar #topbarPdfBtn,#projectTopbar #topbarDxfBtn{display:none!important}#projectTopbar .projectTopbarMeta strong{font-size:15px!important}}';document.head.append(topbarStyle);
  $('#topbarImportBtn').onclick=()=>$('#projectFile').click();$('#topbarAddPartBtn').onclick=()=>$('#addPart')?.click();$('#topbarCalcBtn').onclick=()=>$('#calcBtn')?.click();
  window.getProjectMaterials=()=>materialRecords().filter(x=>projectMaterialNames().includes(x.name));
  window.getProjectSnapshot=()=>{const p=active();return p?JSON.parse(JSON.stringify(p)):null};
  const newProjectButton=document.createElement('button');newProjectButton.id='newProjectBtn';newProjectButton.type='button';newProjectButton.className='newProjectButton';newProjectButton.textContent='＋ Новый проект';panel.querySelector('.projectsContent')?.prepend(newProjectButton);newProjectButton.addEventListener('click',newProject);panelHeader.querySelector('.projectSectionNavAdd')?.addEventListener('click',()=>newProjectButton.click());
  const saveProjectButton=document.createElement('button');saveProjectButton.id='saveProjectBtn';saveProjectButton.type='button';saveProjectButton.className='saveProjectButton';saveProjectButton.textContent='Сохранить проект';newProjectButton.insertAdjacentElement('afterend',saveProjectButton);
  const projectSaveStatus=document.createElement('span');projectSaveStatus.id='projectSaveStatus';projectSaveStatus.setAttribute('role','status');saveProjectButton.insertAdjacentElement('afterend',projectSaveStatus);
  const setSaveStatus=(text,kind='saved')=>{projectSaveStatus.textContent=text;projectSaveStatus.dataset.state=kind};
  saveProjectButton.addEventListener('click',()=>{const project=collect();renderCatalog();updateProjectStatus();setSaveStatus(`Сохранено «${project.name}»`);});
  const newProjectStyle=document.createElement('style');newProjectStyle.textContent='.newProjectButton,.saveProjectButton{display:block!important;width:100%!important;margin:0 0 7px!important;padding:9px 12px!important;border:1px solid #b9d9ee!important;border-radius:5px!important;background:#eef7ff!important;color:#244064!important;font-size:12px!important;font-weight:600!important;text-align:left!important;cursor:pointer!important}.saveProjectButton{background:#1687f5!important;border-color:#1687f5!important;color:#fff!important}.newProjectButton:hover{background:#dff0ff!important;border-color:#8fc2e6!important}.saveProjectButton:hover{background:#1479e5!important;border-color:#1479e5!important}#projectSaveStatus{display:block!important;min-height:18px!important;margin:0 0 10px!important;color:#71829a!important;font-size:10px!important}#projectSaveStatus[data-state="saving"]{color:#b7791f!important}#projectSaveStatus[data-state="saved"]{color:#4b8b68!important}';document.head.append(newProjectStyle);
  $('#addProjectMaterial').addEventListener('click',()=>{preserveEmptyGroups=true},{capture:true});
  let autosaveTimer=0;
  const scheduleAutosave=event=>{
    if(event.target.closest?.('#projectMaterialSearch'))return;
    if(!event.target.closest?.('#projectName,#projectNote,[data-material-field],#projectQty'))return;
    clearTimeout(autosaveTimer);
    setSaveStatus('Сохраняем…','saving');
    autosaveTimer=setTimeout(()=>{const project=collect();setSaveStatus(`Автосохранено «${project.name}»`);},300);
  };
  panel.addEventListener('input',scheduleAutosave);
  panel.addEventListener('change',scheduleAutosave);
  renderList();renderCatalog();persist();
})();
