(function(){
  const panel=document.querySelector('#projectsPanel');
  if(!panel)return;
  const statusKey='cuttingProjectStatus',noteKey='cuttingProjectNotes';
  const names={draft:'Черновик',working:'В работе',calculated:'Рассчитан',done:'Завершён',archived:'Архив'};
  const read=key=>{try{return JSON.parse(localStorage.getItem(key)||'{}')}catch{return{}}};
  const write=(key,value)=>localStorage.setItem(key,JSON.stringify(value));
  const statuses=read(statusKey),notes=read(noteKey),$=s=>panel.querySelector(s);
  const currentItem=()=>panel.querySelector('.projectItem.active'),currentId=()=>currentItem()?.dataset.projectId||'';
  const currentStatus=()=>statuses[currentId()]||'draft';
  const setStatus=status=>{const id=currentId();if(!id)return;statuses[id]=status;write(statusKey,statuses);render()};
  const render=()=>{const id=currentId(),status=currentStatus(),badge=$('#projectStatus');if(badge){badge.textContent=names[status];badge.className=`projectStatus ${status}`}const finish=$('#finishProjectBtn'),archive=$('#archiveProjectBtn');if(finish)finish.textContent=status==='done'?'Вернуть проект в работу':'Завершить проект';if(archive)archive.textContent=status==='archived'?'Разархивировать':'Архивировать';panel.querySelectorAll('.projectItem').forEach(item=>{const s=statuses[item.dataset.projectId]||'draft',select=item.querySelector('.projectSelect');if(select&&!select.querySelector('.projectStatus'))select.insertAdjacentHTML('beforeend',`<small class="projectStatus ${s}">${names[s]}</small>`)});const note=$('#projectNote');if(note)note.value=notes[id]||''};
  const head=panel.querySelector('.projectsContent');
  if(head&&!$('#projectStatus')){const name=$('#projectName'),identity=document.createElement('div');identity.className='projectIdentity';name.parentElement.parentElement.insertBefore(identity,name.parentElement);identity.append(name.parentElement);identity.insertAdjacentHTML('beforeend','<span id="projectStatus" class="projectStatus draft">Черновик</span>');const note=document.createElement('label');note.className='projectNoteLabel';note.innerHTML='Примечание<textarea id="projectNote" rows="2" placeholder="Комментарий к проекту"></textarea>';identity.after(note);const actions=document.createElement('div');actions.className='projectActions';actions.innerHTML='<button id="finishProjectBtn" type="button" class="secondary">Завершить проект</button><button id="archiveProjectBtn" type="button" class="secondary">Архивировать</button>';note.after(actions);$('#finishProjectBtn').onclick=()=>setStatus(currentStatus()==='done'?'working':'done');$('#archiveProjectBtn').onclick=()=>setStatus(currentStatus()==='archived'?'working':'archived');$('#projectNote').addEventListener('input',()=>{const id=currentId();if(id){notes[id]=$('#projectNote').value;write(noteKey,notes)}})}
  panel.addEventListener('click',e=>{if(e.target.closest('#saveProjectBtn')){if(currentStatus()==='draft')setStatus('working');else render()}if(e.target.closest('.projectSelect'))setTimeout(render,0)});
  document.addEventListener('input',e=>{if(e.target.closest('#sheets,#parts,#settingsPanel')&&currentId()&&currentStatus()!=='archived')setStatus('working')});
  window.projectCalculationFinished=ok=>{if(ok&&currentId())setStatus('calculated')};
  const observer=new MutationObserver(render);observer.observe(panel.querySelector('#projectList')||panel,{childList:true,subtree:true});
  const style=document.createElement('style');style.textContent='.projectIdentity{display:flex;align-items:flex-end;gap:8px}.projectIdentity .projectNameLabel{flex:1}.projectStatus{display:inline-block;padding:3px 7px;border-radius:999px;font-size:10px;font-weight:700;background:#edf1f3;color:#52636c;white-space:nowrap}.projectStatus.working{background:#fff2cc;color:#8b5e00}.projectStatus.calculated{background:#dff5e8;color:#197044}.projectStatus.done{background:#dceaff;color:#245a9b}.projectStatus.archived{background:#e7e7e7;color:#666}.projectNoteLabel{display:block!important;margin-top:8px;font-size:11px;color:#52636c}.projectNoteLabel textarea{display:block;width:100%;box-sizing:border-box;margin-top:4px;padding:7px;border:1px solid #cbd6dc;border-radius:5px;resize:vertical;font:inherit}.projectActions{display:flex!important;gap:6px;margin:8px 0}.projectActions button{padding:6px 9px;font-size:11px}.projectSelect .projectStatus{margin-left:6px}.projectSelect{display:flex!important;align-items:center;gap:5px}.projectSelect strong{font-weight:600}.projectSelect small{font-size:10px!important}html body main #sidebarRoot .projectNameLabel,html body main #sidebarRoot .projectsActions,html body main #sidebarRoot #projectList{display:block!important}html body main #sidebarRoot .projectsActions{display:flex!important}html body main #sidebarRoot .projectAdvanced{display:none!important}';document.head.append(style);render();
})();
