(function(){
  const slider=document.querySelector('#mapScale'), output=document.querySelector('#mapScaleValue');
  if(!slider||!output)return;
  let draftRefreshQueued=false;
  const saved=Number(localStorage.getItem('cuttingMapScale'));
  if(saved>=25&&saved<=100)slider.value=String(saved);
  const numberStyle=(el,prop)=>{const value=parseFloat(el.style[prop]);return Number.isFinite(value)?value:null};
  const scaleBoard=(board,zoom)=>{
    const props=['width','height'];
    props.forEach(prop=>{const current=numberStyle(board,prop),applied=Number(board.dataset[`scaled${prop}`]);if(current!==null&&(!Number.isFinite(applied)||Math.abs(current-applied)>.1))board.dataset[`base${prop}`]=String(current);const base=Number(board.dataset[`base${prop}`]);if(Number.isFinite(base)){board.style[prop]=`${base*zoom}px`;board.dataset[`scaled${prop}`]=String(base*zoom)}});
    board.querySelectorAll('.piece').forEach(piece=>{['left','top','width','height'].forEach(prop=>{const current=numberStyle(piece,prop),applied=Number(piece.dataset[`scaled${prop}`]);if(current!==null&&(!Number.isFinite(applied)||Math.abs(current-applied)>.1))piece.dataset[`base${prop}`]=String(current);const base=Number(piece.dataset[`base${prop}`]);if(Number.isFinite(base)){const scaled=`${base*zoom}px`;piece.style[prop]=scaled;piece.dataset[`scaled${prop}`]=String(base*zoom);if(piece.classList.contains('draftUnplacedPiece')){const cssVar={left:'--draft-piece-left',top:'--draft-piece-top',width:'--draft-piece-width',height:'--draft-piece-height'}[prop];if(cssVar)piece.style.setProperty(cssVar,scaled)}}})});
    const area=board.closest('#unplaced');
    if(area){const current=numberStyle(area,'minHeight'),applied=Number(area.dataset.scaledMinHeight);if(current!==null&&(!Number.isFinite(applied)||Math.abs(current-applied)>.1))area.dataset.baseMinHeight=String(current);const base=Number(area.dataset.baseMinHeight);if(Number.isFinite(base)){area.style.setProperty('min-height',`${Math.max(180,base*zoom)}px`,'important');area.dataset.scaledMinHeight=String(base*zoom)}area.style.setProperty('flex','1 1 auto','important')}
  };
  const refreshDraftPreview=()=>{if(draftRefreshQueued)return;draftRefreshQueued=true;requestAnimationFrame(()=>{draftRefreshQueued=false;if((typeof bestResult==='undefined'||!bestResult)&&typeof renderDraftPreview==='function')renderDraftPreview()})};
  const apply=(refreshDraft=true)=>{const value=Number(slider.value)||100, zoom=value/100,fullscreen=document.body.classList.contains('workspaceFullscreen');output.value=`${value}%`;output.textContent=`${value}%`;localStorage.setItem('cuttingMapScale',String(value));document.querySelectorAll('#layouts .layout,#layouts .draftLayout').forEach(el=>{if(fullscreen){let baseWidth=Number(el.dataset.fullscreenBaseWidth);if(!Number.isFinite(baseWidth)){baseWidth=el.getBoundingClientRect().width/zoom;el.dataset.fullscreenBaseWidth=String(baseWidth)}el.style.setProperty('width',`${baseWidth*zoom}px`,'important')}else{el.style.width=`${value}%`;delete el.dataset.fullscreenBaseWidth}const sheetWidth=el.querySelector('.sheet')?.getBoundingClientRect().width||0;if(sheetWidth)el.style.setProperty('--measure-arrow-size',`${Math.max(6,Math.min(18,sheetWidth/40))*0.7}px`)});const board=document.querySelector('#unplacedBoard');if(board&&!board.querySelector('.draftUnplacedPiece'))scaleBoard(board,zoom);if(refreshDraft)refreshDraftPreview()};
  slider.addEventListener('input',()=>apply(true));
  let savedFullscreenInline=null;
  const captureInline=(element,properties)=>Object.fromEntries(properties.map(property=>[property,[element.style.getPropertyValue(property),element.style.getPropertyPriority(property)]]));
  const restoreInline=(element,properties)=>Object.entries(properties).forEach(([property,[value,priority]])=>{if(value)element.style.setProperty(property,value,priority);else element.style.removeProperty(property)});
  const setFullscreenLayout=active=>{
    const main=document.querySelector('main'),result=main?.querySelector('.result');if(!main||!result)return;
    if(active){
      if(!savedFullscreenInline)savedFullscreenInline={main:captureInline(main,['grid-template-columns']),result:captureInline(result,['position','grid-column','top','right','bottom','left','width','height','margin'])};
      main.style.setProperty('grid-template-columns','minmax(0,1fr)','important');result.style.setProperty('position','fixed','important');result.style.setProperty('grid-column','1','important');['top','right','bottom','left'].forEach(property=>result.style.setProperty(property,'0','important'));result.style.setProperty('width','100vw','important');result.style.setProperty('height','100vh','important');result.style.setProperty('margin','0','important');return;
    }
    if(savedFullscreenInline){restoreInline(main,savedFullscreenInline.main);restoreInline(result,savedFullscreenInline.result);savedFullscreenInline=null}
  };
  window.addEventListener('resize',()=>{apply(false);setFullscreenLayout(document.body.classList.contains('workspaceFullscreen'))});
  let applyQueued=false;const queueApply=()=>{if(applyQueued)return;applyQueued=true;requestAnimationFrame(()=>{applyQueued=false;apply(false)})};const observer=new MutationObserver(queueApply),layoutsRoot=document.querySelector('#layouts'),unplacedBoard=document.querySelector('#unplacedBoard');if(layoutsRoot)observer.observe(layoutsRoot,{childList:true,subtree:true});if(unplacedBoard)observer.observe(unplacedBoard,{childList:true,subtree:true});
  const toolbar=document.querySelector('main>.result .resultToolbar');
  if(toolbar){
    const button=document.createElement('button');button.type='button';button.id='workspaceFullscreenToggle';button.className='secondary workspaceFullscreenToggle';button.setAttribute('aria-pressed','false');button.title='Развернуть рабочую область';
    const sync=active=>{if(active){const zoom=(Number(slider.value)||100)/100;document.querySelectorAll('#layouts .layout,#layouts .draftLayout').forEach(el=>el.dataset.fullscreenBaseWidth=String(el.getBoundingClientRect().width/zoom))}document.body.classList.toggle('workspaceFullscreen',active);setFullscreenLayout(active);apply(false);button.setAttribute('aria-pressed',String(active));button.innerHTML=active?'<span class="material-symbols-rounded" aria-hidden="true">close_fullscreen</span>':'<span class="material-symbols-rounded" aria-hidden="true">open_in_full</span>';button.title=active?'Выйти из полного экрана (Esc)':'Развернуть рабочую область на весь экран';requestAnimationFrame(()=>{window.dispatchEvent(new Event('resize'));if(active){result.style.setProperty('left','0','important');setTimeout(()=>result.style.setProperty('left','0','important'),0)}})};
    button.innerHTML='<span class="material-symbols-rounded" aria-hidden="true">open_in_full</span>';
    button.addEventListener('click',()=>sync(!document.body.classList.contains('workspaceFullscreen')));document.addEventListener('keydown',event=>{if(event.key==='Escape'&&document.body.classList.contains('workspaceFullscreen'))sync(false)});toolbar.append(button);
  }
  const style=document.createElement('style');style.textContent='#layouts{display:flex!important;flex-wrap:wrap!important;align-items:flex-start!important;align-content:flex-start!important;gap:16px!important}#layouts .layout{flex:0 0 auto!important;margin:0!important}.mapScaleControl{display:inline-flex;align-items:center;gap:8px;margin-left:auto;font-size:12px;color:#52636c;white-space:nowrap}.mapScaleControl input{width:150px;accent-color:#2c9c69}.mapScaleControl output{display:inline-block;min-width:38px;font-variant-numeric:tabular-nums;color:#263943;font-weight:600}.workspaceFullscreenToggle{display:inline-flex;align-items:center;justify-content:center;flex:0 0 auto!important;width:34px!important;height:34px!important;padding:7px!important;min-height:34px;border:1px solid #d7e1ec!important;border-radius:4px!important;background:#fff!important;color:#244064!important;font:600 13px Inter,Segoe UI,Arial,sans-serif!important;cursor:pointer}.workspaceFullscreenToggle .material-symbols-rounded{font-size:19px;line-height:1}.workspaceFullscreenToggle:hover{background:#f2f7ff!important;border-color:#9dccf4!important;color:#1479e5!important}@media(max-width:600px){.mapScaleControl{width:100%;margin:4px 0 0}.mapScaleControl input{flex:1}.workspaceFullscreenToggle{margin-left:auto}}';document.head.append(style);
  apply(false);refreshDraftPreview();
})();
