/* Narrow workspace rail with one contextual drawer. */
(function(){
  const rail=document.querySelector('.appRail');
  const root=document.querySelector('#sidebarRoot');
  const result=document.querySelector('main > .result');
  if(!rail||!root||!result)return;
  const railMark=rail.querySelector('.railMark');
  if(railMark){
    railMark.removeAttribute('title');
    railMark.dataset.tooltip='Развернуть боковую панель    Ctrl+Shift+S';
    railMark.setAttribute('aria-label','Развернуть боковую панель, Ctrl+Shift+S');
    const logoMarkup='<img src="logo.png" alt="Раскройщик">';
    const leftPanelOpenMarkup='<svg class="sidebarArrowIcon" viewBox="0 0 24 24" aria-label="Arrow Right"><path d="M8 4l8 8-8 8z"></path></svg>';
    railMark.innerHTML=logoMarkup;
    railMark.addEventListener('mouseenter',()=>{railMark.innerHTML=leftPanelOpenMarkup});
    railMark.addEventListener('mouseleave',()=>{railMark.innerHTML=logoMarkup});
  }
  document.querySelector('.topNav')?.remove();
  rail.querySelector('[aria-label="Раскрой"]')?.remove();
  const style=document.createElement('style');
  style.textContent=`
    :root{--ui-rail-width:64px;--ui-drawer-width:820px;--ui-drawer-wide-width:900px}
    main .appRail{position:absolute!important;left:0!important;top:0!important;bottom:0!important;width:var(--ui-rail-width)!important;display:flex!important;flex-direction:column!important;align-items:center!important;gap:6px!important;padding:14px 8px!important;background:#fff!important;border:0!important;border-right:1px solid #e7eef5!important;box-shadow:2px 0 14px rgba(32,70,112,.06)!important;z-index:40!important}
    .railMark{display:grid;place-items:center;width:40px;height:40px;margin-bottom:12px;border-radius:12px;background:#eef6ff;color:#1687f5;font-size:20px;font-weight:700}
    .railSectionLabel{width:100%;margin:0 0 2px;text-align:center;color:#9aaac0;font-size:9px;font-weight:700;letter-spacing:.08em;text-transform:uppercase}
    .railSectionLabelService{margin-top:14px;padding-top:14px;border-top:1px solid #edf1f6}
    .railMaterialLogo{display:block;justify-self:center;width:21px;height:21px;object-fit:contain;opacity:.9;transform:translateX(-2.5px)}
    .railDetailsLogo{display:block;justify-self:center;width:21px;height:21px;object-fit:contain;opacity:.82}
    main .appRail .railLink{display:grid!important;place-items:center!important;gap:3px!important;width:48px!important;min-height:48px!important;padding:6px 2px!important;border:0!important;border-radius:12px!important;background:transparent!important;color:#71829a!important;cursor:pointer!important;transition:background 140ms ease,color 140ms ease,box-shadow 140ms ease!important}
    main .appRail .railLink span:last-child,.railSectionLabel{display:none!important}
    main .appRail .railLink .material-symbols-rounded{font-size:21px;line-height:1}
    main .appRail .railLink:hover{background:#f1f7ff!important;color:#1687f5!important;box-shadow:none!important}
    main .appRail .railLink.active{background:#e1f1ff!important;color:#1687f5!important;box-shadow:inset 0 0 0 1px #c7e2fb!important}
    main #sidebarRoot{left:var(--ui-rail-width)!important;width:var(--ui-drawer-width)!important;transform:translateX(-105%)!important;opacity:0!important;pointer-events:none!important;z-index:1200!important;box-shadow:12px 0 30px rgba(31,42,55,.14)!important;transition:transform 200ms ease,opacity 200ms ease,width 200ms ease!important}
    body.workspaceDrawerWide main #sidebarRoot{width:var(--ui-drawer-wide-width)!important}
    body.workspaceDrawerOpen main #sidebarRoot{transform:translateX(0)!important;opacity:1!important;pointer-events:auto!important}
    main>.result{left:var(--ui-rail-width)!important;transition:left 200ms ease!important}
    body.workspaceDrawerOpen main>.result{left:var(--ui-rail-width)!important}
    body.workspaceDrawerOpen main .appRail{box-shadow:2px 0 14px rgba(32,70,112,.10)!important}
    html body main #sidebarRoot>.drawerPanelHidden{display:none!important}
    body.projectOnlyMode main #sidebarRoot>#projectsPanel .projectsContent{display:block!important;min-height:70px!important}
    .drawerWidthToggle{display:none!important;align-items:center;justify-content:center;position:static;width:28px;height:28px;flex:0 0 28px;margin:0 0 0 auto!important;padding:0;border:0;border-radius:7px;background:transparent;color:#71829a;cursor:pointer;font:inherit}
    #partsPanel .detailsTableBar .drawerWidthToggle{display:inline-flex!important}
    #partsPanel .detailsExpandButton{display:none!important}
    body.workspaceDrawerOpen #partsPanel .drawerWidthToggle{display:inline-flex!important}
    .drawerWidthToggle:hover{background:#eef6ff;color:#1687f5}
    .drawerWidthToggle .material-symbols-rounded{font-size:18px}
    @media(max-width:900px){main .appRail{position:relative!important;top:auto!important;bottom:auto!important;width:100%!important;height:58px!important;flex-direction:row!important;justify-content:flex-start!important;overflow:auto!important;padding:5px 8px!important}.railMark,.railSectionLabel{display:none!important}main .appRail .railLink{width:58px!important;min-width:58px!important}.railSectionLabelService{margin:0;padding:0;border:0}main #sidebarRoot{left:0!important;width:100%!important;transform:translateY(-105%)!important;max-height:70vh!important}body.workspaceDrawerOpen main #sidebarRoot,body.workspaceDrawerWide main #sidebarRoot{transform:translateY(0)!important;width:100%!important}main>.result,body.workspaceDrawerOpen main>.result{left:0!important}}
  `;
  style.textContent+=`main .appRail>.railMark{display:grid!important;overflow:hidden;background:#fff!important;border:1px solid #e5edf5!important}main .appRail>.railMark img{display:block;width:32px;height:32px;object-fit:contain}`;
  document.head.append(style);
  const panels=['projectsPanel','materialsPanel','partsPanel','settingsPanel'].map(id=>document.getElementById(id)).filter(Boolean);
  const partsPanel=document.querySelector('#partsPanel');
  const settingsPanel=document.querySelector('#settingsPanel');
  const edgeVisibilityKey='cuttingShowDetailEdges';
  const edgeSetting=document.createElement('label');
  edgeSetting.className='detailEdgeVisibilitySetting';
  edgeSetting.innerHTML='Показывать в деталях кромки<input id="showDetailEdges" type="checkbox">';
  const edgeSettingInput=edgeSetting.querySelector('input');
  edgeSettingInput.checked=localStorage.getItem(edgeVisibilityKey)==='true';
  const settingsAnchor=settingsPanel?.querySelector('.materialsDb')||settingsPanel?.querySelector('.settingsHead');
  settingsAnchor?.after(edgeSetting);
  const edgeVisibilityStyle=document.createElement('style');edgeVisibilityStyle.textContent='html body.detailEdgesHidden .pieceEdge{display:none!important}';document.head.append(edgeVisibilityStyle);
  const settingsControlsStyle=document.createElement('style');settingsControlsStyle.textContent='html body #settingsPanel.settingsOpen .textureSetting,html body #settingsPanel.settingsOpen .detailEdgeVisibilitySetting{display:flex!important;align-items:center!important;justify-content:space-between!important;gap:12px!important;text-align:left!important;opacity:1!important}html body #settingsPanel.settingsOpen .textureSetting input[type="checkbox"],html body #settingsPanel.settingsOpen .detailEdgeVisibilitySetting input[type="checkbox"]{appearance:none!important;display:block!important;position:relative!important;flex:0 0 40px!important;width:40px!important;height:20px!important;margin:0!important;padding:0!important;border:1px solid #9fb5c7!important;border-radius:999px!important;background:#eef3f7!important;box-shadow:none!important;cursor:pointer!important}html body #settingsPanel.settingsOpen .textureSetting input[type="checkbox"]::before,html body #settingsPanel.settingsOpen .detailEdgeVisibilitySetting input[type="checkbox"]::before{content:""!important;position:absolute!important;left:2px!important;top:2px!important;width:14px!important;height:14px!important;border-radius:50%!important;background:#8fa5b5!important;transition:transform .15s ease,background .15s ease!important}html body #settingsPanel.settingsOpen .textureSetting input[type="checkbox"]:checked,html body #settingsPanel.settingsOpen .detailEdgeVisibilitySetting input[type="checkbox"]:checked{background:#b8def6!important;border-color:#1687f5!important}html body #settingsPanel.settingsOpen .textureSetting input[type="checkbox"]:checked::before,html body #settingsPanel.settingsOpen .detailEdgeVisibilitySetting input[type="checkbox"]:checked::before{transform:translateX(20px)!important;background:#1687f5!important}';document.head.append(settingsControlsStyle);
  const settingsControlsFallback=document.createElement('style');settingsControlsFallback.textContent='html body #settingsPanel .textureSetting,html body #settingsPanel .detailEdgeVisibilitySetting{display:flex!important;align-items:center!important;justify-content:space-between!important;gap:12px!important;text-align:left!important;opacity:1!important}html body #settingsPanel .textureSetting input[type="checkbox"],html body #settingsPanel .detailEdgeVisibilitySetting input[type="checkbox"]{appearance:none!important;display:block!important;position:relative!important;flex:0 0 40px!important;width:40px!important;height:20px!important;margin:0!important;padding:0!important;border:1px solid #9fb5c7!important;border-radius:999px!important;background:#eef3f7!important;box-shadow:none!important;cursor:pointer!important}html body #settingsPanel .textureSetting input[type="checkbox"]::before,html body #settingsPanel .detailEdgeVisibilitySetting input[type="checkbox"]::before{content:""!important;position:absolute!important;left:2px!important;top:2px!important;width:14px!important;height:14px!important;border-radius:50%!important;background:#8fa5b5!important;transition:transform .15s ease,background .15s ease!important}html body #settingsPanel .textureSetting input[type="checkbox"]:checked,html body #settingsPanel .detailEdgeVisibilitySetting input[type="checkbox"]:checked{background:#b8def6!important;border-color:#1687f5!important}html body #settingsPanel .textureSetting input[type="checkbox"]:checked::before,html body #settingsPanel .detailEdgeVisibilitySetting input[type="checkbox"]:checked::before{transform:translateX(20px)!important;background:#1687f5!important}';document.head.append(settingsControlsFallback);
  const calculationControlsStyle=document.createElement('style');calculationControlsStyle.textContent='html body #settingsPanel .calculationModeChecks{display:flex!important;flex-direction:column!important;gap:10px!important;margin:0 14px!important}html body #settingsPanel .calculationModeChecks label{display:flex!important;align-items:center!important;justify-content:space-between!important;gap:12px!important;text-align:left!important;opacity:1!important}html body #settingsPanel .calculationModeChecks input[type="checkbox"]{appearance:none!important;display:block!important;position:relative!important;flex:0 0 40px!important;width:40px!important;height:20px!important;margin:0!important;padding:0!important;border:1px solid #9fb5c7!important;border-radius:999px!important;background:#eef3f7!important;box-shadow:none!important;cursor:pointer!important}html body #settingsPanel .calculationModeChecks input[type="checkbox"]::before{content:""!important;position:absolute!important;left:2px!important;top:2px!important;width:14px!important;height:14px!important;border-radius:50%!important;background:#8fa5b5!important;transition:transform .15s ease,background .15s ease!important}html body #settingsPanel .calculationModeChecks input[type="checkbox"]:checked{background:#b8def6!important;border-color:#1687f5!important}html body #settingsPanel .calculationModeChecks input[type="checkbox"]:checked::before{transform:translateX(20px)!important;background:#1687f5!important}';document.head.append(calculationControlsStyle);
  const syncDetailEdges=()=>document.body.classList.toggle('detailEdgesHidden',!edgeSettingInput.checked);
  edgeSettingInput.addEventListener('change',()=>{localStorage.setItem(edgeVisibilityKey,String(edgeSettingInput.checked));syncDetailEdges()});
  syncDetailEdges();
  const detailsDrawerModeKey='cuttingDetailsDrawerWide';
  const savedDetailsDrawerWide=()=>localStorage.getItem(detailsDrawerModeKey)==='1';
  const saveDetailsDrawerMode=wide=>localStorage.setItem(detailsDrawerModeKey,wide?'1':'0');
  const drawerItems=[...root.children];
  const materialButton=rail.querySelector('[aria-label="Материалы"]');
  if(materialButton){materialButton.removeAttribute('data-drawer-target');materialButton.setAttribute('aria-label','База материалов');materialButton.title='База материалов';materialButton.querySelector('span:last-child')?.replaceChildren(document.createTextNode('База материалов'))}
  const reportButton=document.createElement('button');reportButton.type='button';reportButton.className='railLink';reportButton.setAttribute('data-drawer-close','');reportButton.setAttribute('aria-label','Отчёты');reportButton.title='Отчёты';reportButton.innerHTML='<span class="material-symbols-rounded" aria-hidden="true">assessment</span><span>Отчёты</span>';rail.querySelector('.railSectionLabelService')?.before(reportButton);
  const buttons=[...new Set([...rail.querySelectorAll('[data-drawer-target],[data-drawer-close]'),materialButton].filter(Boolean))];
  rail.querySelector('[aria-label="Проекты"] .material-symbols-rounded')?.replaceChildren(document.createTextNode('work'));
  const materialIcon=rail.querySelector('[aria-label="База материалов"] .material-symbols-rounded');
  if(materialIcon){const logo=document.createElement('img');logo.className='railMaterialLogo';logo.src='assets/materials-works-logo.png';logo.alt='';materialIcon.replaceWith(logo)}
  const detailsIcon=rail.querySelector('[aria-label="Детали"] .material-symbols-rounded');
  if(detailsIcon){const logo=document.createElement('img');logo.className='railDetailsLogo';logo.src='assets/details-list-logo.png';logo.alt='';detailsIcon.replaceWith(logo)}
  const syncGeometry=opened=>{const mobile=window.matchMedia('(max-width:900px)').matches,railWidth=mobile?0:(document.body.classList.contains('workspaceRailExpanded')?286:64),detailsOpen=opened&&partsPanel&&!partsPanel.classList.contains('drawerPanelHidden'),drawerWidth=mobile?0:(document.body.classList.contains('workspaceDrawerWide')?900:detailsOpen?470:820);root.style.setProperty('left',`${railWidth}px`,'important');root.style.setProperty('width',mobile?'100%':`${drawerWidth}px`,'important');result.style.setProperty('left',`${railWidth}px`,'important');document.querySelector('.sidebarResize')?.style.setProperty('display','none','important')};
  let activeDrawerMode='';
  const setActive=(id,mode='')=>buttons.forEach(button=>button.classList.toggle('active',button.dataset.drawerTarget===id&&(!mode||button.getAttribute('aria-label')===mode)||(!id&&button.dataset.drawerClose!==undefined&&button.title==='Раскрой')));
  const close=()=>{if(document.body.classList.contains('workspaceDrawerOpen')&&!partsPanel?.classList.contains('drawerPanelHidden'))saveDetailsDrawerMode(document.body.classList.contains('workspaceDrawerWide'));document.body.classList.remove('workspaceDrawerOpen','workspaceDrawerWide','projectOnlyMode');activeDrawerMode='';drawerItems.forEach(item=>{item.classList.remove('drawerPanelHidden');item.style.removeProperty('display')});panels.forEach(panel=>panel.classList.remove('drawerPanelHidden'));setActive(null);syncGeometry(false)};
  const open=(id,mode='')=>{const target=document.getElementById(id);if(!target)return;activeDrawerMode=mode;document.body.classList.toggle('projectOnlyMode',mode==='Проекты');document.querySelector('.projectPanelHeader strong')?.replaceChildren(document.createTextNode(mode==='Проекты'?'Проекты':'Материалы и параметры'));document.body.classList.toggle('workspaceDrawerWide',id==='partsPanel'&&savedDetailsDrawerWide());drawerItems.forEach(item=>{const show=item===target||(id==='projectsPanel'&&item.classList.contains('projectPanelHeader'));item.classList.toggle('drawerPanelHidden',!show);item.style.setProperty('display',show?'flex':'none','important')});panels.forEach(panel=>panel.classList.toggle('drawerPanelHidden',panel!==target));target.classList.remove('hidden');if(id==='settingsPanel'){target.classList.add('settingsOpen','sectionExpanded');target.classList.remove('sectionCollapsed');target.querySelectorAll('.sectionBodyHidden').forEach(x=>x.classList.remove('sectionBodyHidden'))}document.body.classList.add('workspaceDrawerOpen');setActive(id,mode);syncGeometry(true)};
  const sidebarPanel=document.createElement('aside');
  sidebarPanel.id='workspaceSidebarPanel';
  sidebarPanel.setAttribute('aria-label','Боковая панель рабочего пространства');
  sidebarPanel.innerHTML='<div class="workspaceSidebarHead"><div class="workspaceSidebarBrand"><img src="logo.png" alt=""><strong>Раскройщик</strong></div><button type="button" class="workspaceSidebarToggle" data-tooltip="Свернуть боковую панель    Ctrl+Shift+S" aria-label="Свернуть боковую панель"><svg class="sidebarArrowIcon" viewBox="0 0 24 24" aria-label="Arrow Left"><path d="M16 4l-8 8 8 8z"></path></svg></button></div><div class="workspaceSidebarBody"><div class="workspaceSidebarSection"><div class="workspaceSidebarLabel">Команды</div><div class="workspaceSidebarCommands"></div></div><div class="workspaceSidebarSection"><div class="workspaceSidebarLabel">Проекты</div><div class="workspaceSidebarProjects"></div></div><div class="workspaceSidebarSection"><div class="workspaceSidebarLabel">Закреплённые проекты</div><div class="workspaceSidebarPinned"></div></div></div>';
  document.body.append(sidebarPanel);
  const sidebarCommands=sidebarPanel.querySelector('.workspaceSidebarCommands');
  const sidebarProjects=sidebarPanel.querySelector('.workspaceSidebarProjects');
  const sidebarPinned=sidebarPanel.querySelector('.workspaceSidebarPinned');
  const pinnedProjectsKey='cuttingPinnedProjects';
  const readProjects=()=>{try{const value=JSON.parse(localStorage.getItem('cuttingProjects')||'[]');return Array.isArray(value)?value:[]}catch{return[]}};
  const readPinned=()=>{try{const value=JSON.parse(localStorage.getItem(pinnedProjectsKey)||'[]');return new Set(Array.isArray(value)?value.map(String):[])}catch{return new Set()}};
  const savePinned=set=>localStorage.setItem(pinnedProjectsKey,JSON.stringify([...set]));
  const commandLabel=button=>button.getAttribute('aria-label')||button.querySelector('span:last-child')?.textContent.trim()||'Команда';
  const commandIcon=button=>button.querySelector('.material-symbols-rounded, img')?.cloneNode(true)||document.createTextNode('•');
  const sidebarCommandClick=button=>{button.click();sidebarPanel.classList.remove('isPinned');sidebarPanel.classList.remove('isExpanded')};
  const renderSidebarCommands=()=>{sidebarCommands.replaceChildren();buttons.forEach(button=>{if(!button)return;const item=document.createElement('button');item.type='button';item.className='workspaceSidebarCommand';item.title=commandLabel(button);item.setAttribute('aria-label',commandLabel(button));item.append(commandIcon(button));const label=document.createElement('span');label.textContent=commandLabel(button);item.append(label);item.addEventListener('click',()=>sidebarCommandClick(button));sidebarCommands.append(item)})};
  const renderSidebarProjects=()=>{const projects=readProjects().filter(project=>project&&project.status!=='archived'&&project.id);const pinned=readPinned();sidebarProjects.replaceChildren();sidebarPinned.replaceChildren();const makeEmpty=message=>{const empty=document.createElement('div');empty.className='workspaceSidebarEmpty';empty.textContent=message;return empty};
    if(!projects.length)sidebarProjects.append(makeEmpty('Сохранённых проектов пока нет.'));
    projects.forEach(project=>{const item=document.createElement('div');item.className='workspaceSidebarProject';const select=document.createElement('button');select.type='button';select.className='workspaceSidebarProjectSelect';select.textContent=project.name||'Без названия';select.title=project.name||'Без названия';select.addEventListener('click',()=>{buttons.find(button=>button.getAttribute('aria-label')==='Проекты')?.click();setTimeout(()=>document.querySelector(`#projectList [data-project-id="${CSS.escape(String(project.id))}"] .projectSelect`)?.click(),0);sidebarPanel.classList.remove('isExpanded')});const pin=document.createElement('button');pin.type='button';pin.className='workspaceSidebarPin';pin.textContent=pinned.has(String(project.id))?'★':'☆';pin.title=pinned.has(String(project.id))?'Открепить проект':'Закрепить проект';pin.setAttribute('aria-label',pin.title);pin.addEventListener('click',event=>{event.stopPropagation();const next=readPinned();if(next.has(String(project.id)))next.delete(String(project.id));else next.add(String(project.id));savePinned(next);renderSidebarProjects()});item.append(select,pin);sidebarProjects.append(item)});
    const pinnedProjects=projects.filter(project=>pinned.has(String(project.id)));if(!pinnedProjects.length)sidebarPinned.append(makeEmpty('Нет закреплённых проектов.'));pinnedProjects.forEach(project=>{const item=document.createElement('button');item.type='button';item.className='workspaceSidebarPinnedProject';item.textContent=project.name||'Без названия';item.title=project.name||'Без названия';item.addEventListener('click',()=>{buttons.find(button=>button.getAttribute('aria-label')==='Проекты')?.click();setTimeout(()=>document.querySelector(`#projectList [data-project-id="${CSS.escape(String(project.id))}"] .projectSelect`)?.click(),0);sidebarPanel.classList.remove('isExpanded')});sidebarPinned.append(item)});
  };
  const renderSidebar=()=>{renderSidebarCommands();renderSidebarProjects()};
  const expandSidebar=()=>{renderSidebar();sidebarPanel.classList.add('isExpanded');document.body.classList.add('workspaceRailExpanded');syncGeometry(true)};
  const collapseSidebar=()=>{if(!sidebarPanel.classList.contains('isPinned')){sidebarPanel.classList.remove('isExpanded');document.body.classList.remove('workspaceRailExpanded');syncGeometry(false)}};
  const hideSidebar=()=>{sidebarPanel.classList.remove('isPinned','isExpanded');document.body.classList.remove('workspaceRailExpanded');syncGeometry(false)};
  const toggleSidebar=()=>{if(sidebarPanel.classList.contains('isExpanded'))collapseSidebar();else expandSidebar()};
  sidebarPanel.querySelector('.workspaceSidebarToggle').addEventListener('click',toggleSidebar);
  rail.addEventListener('click',event=>{if(event.target.closest('.railLink,.railUser'))return;toggleSidebar()});
  document.addEventListener('keydown',event=>{if(event.ctrlKey&&event.shiftKey&&event.key.toLowerCase()==='s'){event.preventDefault();sidebarPanel.classList.contains('isExpanded')?hideSidebar():expandSidebar()}});
  const projectList=document.querySelector('#projectList');if(projectList)new MutationObserver(renderSidebarProjects).observe(projectList,{childList:true,subtree:true});window.addEventListener('storage',event=>{if(event.key==='cuttingProjects'||event.key===pinnedProjectsKey)renderSidebarProjects()});
  const sidebarStyle=document.createElement('style');sidebarStyle.textContent=`#workspaceSidebarPanel{position:fixed;left:0;top:0;bottom:0;width:286px;z-index:1300;display:flex;flex-direction:column;background:#fff;border-right:1px solid #dce6ee;box-shadow:10px 0 28px rgba(31,42,55,.16);transform:translateX(-105%);opacity:0;pointer-events:none;transition:transform 180ms ease,opacity 180ms ease;font-family:inherit}#workspaceSidebarPanel.isExpanded{transform:translateX(0);opacity:1;pointer-events:auto}.workspaceSidebarHead{display:flex;align-items:center;gap:10px;height:64px;padding:0 14px;border-bottom:1px solid #edf1f6;color:#263943}.workspaceSidebarBrand{display:flex;align-items:center;gap:9px;min-width:0}.workspaceSidebarBrand img{display:block;width:28px;height:28px;object-fit:contain;border-radius:50%}.workspaceSidebarHead strong{font-size:14px}.workspaceSidebarToggle{display:grid;place-items:center;width:36px;height:36px;padding:0;border:0;border-radius:9px;background:#f1f7ff;color:#1687f5;cursor:pointer}.workspaceSidebarToggle:hover{background:#e1f1ff}.workspaceSidebarToggle .material-symbols-rounded{font-size:20px}.workspaceSidebarBody{overflow:auto;padding:12px 10px 24px}.workspaceSidebarSection{margin-bottom:18px}.workspaceSidebarLabel{padding:0 8px 7px;color:#8193a5;font-size:10px;font-weight:700;letter-spacing:.08em;text-transform:uppercase}.workspaceSidebarCommands{display:grid;gap:2px}.workspaceSidebarCommand,.workspaceSidebarProjectSelect,.workspaceSidebarPinnedProject{display:flex;align-items:center;gap:10px;width:100%;min-height:38px;padding:7px 9px;border:0;border-radius:8px;background:transparent;color:#405668;text-align:left;font:inherit;font-size:12px;cursor:pointer}.workspaceSidebarCommand:hover,.workspaceSidebarProjectSelect:hover,.workspaceSidebarPinnedProject:hover{background:#f1f7ff;color:#1687f5}.workspaceSidebarCommand .material-symbols-rounded,.workspaceSidebarCommand img{width:20px;height:20px;object-fit:contain;font-size:20px;flex:0 0 20px}.workspaceSidebarProject{display:flex;align-items:center;gap:4px}.workspaceSidebarProjectSelect{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.workspaceSidebarPin{flex:0 0 28px;width:28px;height:28px;padding:0;border:0;border-radius:6px;background:transparent;color:#b2bfca;font-size:18px;cursor:pointer}.workspaceSidebarPin:hover{background:#fff4d7;color:#d28a00}.workspaceSidebarPinnedProject{color:#536777}.workspaceSidebarEmpty{padding:5px 8px;color:#9aa9b5;font-size:11px}@media(max-width:900px){#workspaceSidebarPanel{display:none!important}}`;document.head.append(sidebarStyle);
  const sidebarHeadStyle=document.createElement('style');sidebarHeadStyle.textContent='.workspaceSidebarHead{justify-content:space-between!important}.workspaceSidebarToggle{position:relative!important;overflow:visible!important;background:transparent!important;color:#8193a5!important}.workspaceSidebarToggle:hover{background:#f2f4f5!important;color:#8193a5!important}.workspaceSidebarToggle[data-tooltip]::after{content:attr(data-tooltip);position:absolute;left:44px;right:auto;top:50%;z-index:2000;display:block;min-width:max-content;padding:8px 12px;border-radius:18px;background:#101010;color:#fff;box-shadow:0 5px 12px rgba(0,0,0,.28);font:600 12px/1.1 Inter,"Segoe UI",Arial,sans-serif;white-space:pre;opacity:0;pointer-events:none;transform:translateY(-50%) scale(.96);transform-origin:left center;transition:opacity 120ms ease,transform 120ms ease}.workspaceSidebarToggle[data-tooltip]:hover::after{opacity:1;transform:translateY(-50%) scale(1)}.workspaceSidebarToggle .leftPanelCloseIcon{font-size:28px!important;color:#8193a5!important}.thumbnailBarIcon,.leftPanelOpenIcon{display:block;width:20px;height:20px;fill:none;stroke:#8193a5!important;stroke-width:1.8;stroke-linecap:round;stroke-linejoin:round}.thumbnailBarIcon{width:28px;height:28px;stroke-width:2.2}.leftPanelOpenIcon{width:28px;height:28px;stroke-width:2.2}.leftPanelOpenArrow,.leftPanelCloseArrow{fill:#8193a5;stroke:none}';document.head.append(sidebarHeadStyle);
  const sidebarArrowStyle=document.createElement('style');sidebarArrowStyle.textContent='.sidebarArrowIcon{display:block!important;width:16px!important;height:16px!important;fill:#8193a5!important;stroke:none!important}.workspaceSidebarToggle .sidebarArrowIcon{width:16px!important;height:16px!important}';document.head.append(sidebarArrowStyle);
  const expandedRailStyle=document.createElement('style');expandedRailStyle.textContent='html body main .appRail{transition:width 180ms ease!important}html body main .appRail,html body main .appRail *{cursor:url("data:image/svg+xml,%3Csvg xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22 viewBox%3D%220 0 24 24%22%3E%3Cpath d%3D%22M2 12h8m-4-4-4 4 4 4M22 12h-8m4-4 4 4-4 4%22 fill%3D%22none%22 stroke%3D%22%234a4f54%22 stroke-width%3D%222%22 stroke-linecap%3D%22round%22 stroke-linejoin%3D%22round%22%2F%3E%3C%2Fsvg%3E") 12 12,auto!important}html body main .appRail .railLink,html body main .appRail .railLink *{cursor:pointer!important}html body main .appRail>.railMark{position:relative!important;overflow:visible!important}html body main .appRail>.railMark[data-tooltip]::after{content:attr(data-tooltip);position:absolute;left:50px;top:50%;z-index:2000;display:block;min-width:max-content;padding:8px 12px;border-radius:18px;background:#101010;color:#fff;box-shadow:0 5px 12px rgba(0,0,0,.28);font:600 12px/1.1 Inter,"Segoe UI",Arial,sans-serif;white-space:pre;opacity:0;pointer-events:none;transform:translateY(-50%) scale(.96);transform-origin:left center;transition:opacity 120ms ease,transform 120ms ease}html body main .appRail>.railMark[data-tooltip]:hover::after{opacity:1;transform:translateY(-50%) scale(1)}html body.workspaceRailExpanded main .appRail{width:286px!important;box-shadow:2px 0 14px rgba(32,70,112,.10)!important}html body.workspaceRailExpanded main .appRail>*{visibility:hidden!important}html body.workspaceRailExpanded #workspaceSidebarPanel{transform:translateX(0);opacity:1;pointer-events:auto}html body.workspaceRailExpanded main>.result{transition:left 180ms ease!important}@media(max-width:900px){html body.workspaceRailExpanded main .appRail{width:100%!important}html body.workspaceRailExpanded main .appRail>*{visibility:visible!important}}';document.head.append(expandedRailStyle);
  const compactRailCursorStyle=document.createElement('style');compactRailCursorStyle.textContent='html body main .appRail,html body main .appRail *{cursor:url("data:image/svg+xml,%3Csvg xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22 width%3D%2216%22 height%3D%2216%22 viewBox%3D%220 0 24 24%22%3E%3Cpath d%3D%22M2 12h8m-4-4-4 4 4 4M22 12h-8m4-4 4 4-4 4%22 fill%3D%22none%22 stroke%3D%22%234a4f54%22 stroke-width%3D%222%22 stroke-linecap%3D%22round%22 stroke-linejoin%3D%22round%22%2F%3E%3C%2Fsvg%3E") 8 8,auto!important}html body main .appRail .railLink,html body main .appRail .railLink *{cursor:pointer!important}';document.head.append(compactRailCursorStyle);
  const partsTitle=partsPanel?.querySelector(':scope > h2');
  if(partsPanel&&partsTitle&&!partsTitle.querySelector('.drawerWidthToggle')){const toggle=document.createElement('button');toggle.type='button';toggle.className='drawerWidthToggle';toggle.setAttribute('aria-label','Расширить панель деталей');toggle.title='Расширить панель деталей';toggle.innerHTML='<span class="material-symbols-rounded" aria-hidden="true">chevron_right</span>';const bar=partsPanel.querySelector('.detailsTableBar');(bar||partsTitle).append(toggle);toggle.addEventListener('click',event=>{event.stopPropagation();const wide=document.body.classList.toggle('workspaceDrawerWide');saveDetailsDrawerMode(wide);toggle.setAttribute('aria-label',wide?'Свернуть панель деталей':'Расширить панель деталей');toggle.title=wide?'Свернуть панель деталей':'Расширить панель деталей';toggle.querySelector('.material-symbols-rounded').textContent=wide?'chevron_left':'chevron_right';syncGeometry(true)})}
  buttons.forEach(button=>button.addEventListener('click',()=>{const mode=button.getAttribute('aria-label');if(button===materialButton){const library=document.querySelector('.materialsDb'),isOpen=!!library&&!library.classList.contains('hidden');close();if(isOpen){library.classList.add('hidden');button.classList.remove('active');return}library?.classList.remove('hidden');library?.removeAttribute('hidden');button.classList.add('active');return}if(button.dataset.drawerTarget&&button.classList.contains('active')&&document.body.classList.contains('workspaceDrawerOpen'))close();else if(button.dataset.drawerTarget)open(button.dataset.drawerTarget,mode);else close()}));
  document.querySelectorAll('.topNav a').forEach(link=>link.addEventListener('click',event=>{let id=link.getAttribute('href')?.slice(1);if(id==='materialsPanel')id='projectsPanel';if(['projectsPanel','settingsPanel'].includes(id)){event.preventDefault();open(id,id==='projectsPanel'&&link.textContent.trim()==='Проекты'?'Проекты':'Материалы')}else if(link.getAttribute('href')==='#layouts'){close()}}));
  document.addEventListener('keydown',event=>{if(event.key==='Escape')close()});
  document.querySelector('#closeSettings')?.addEventListener('click',close);
  document.querySelector('#settingsBtn')?.addEventListener('click',()=>open('settingsPanel'));
  window.addEventListener('resize',()=>syncGeometry(document.body.classList.contains('workspaceDrawerOpen')));
  const railCommandStyle=document.createElement('style');railCommandStyle.textContent='main .topNav{display:none!important}main .appRail .railLink,main .appRail .railLink:hover,main .appRail .railLink.active{background:transparent!important}main .appRail .railLink.active{box-shadow:none!important;border:0!important}main .appRail .railLink[aria-label="База материалов"] span:last-child{font-size:8px!important;line-height:.95!important;white-space:normal!important;text-align:center!important}';document.head.append(railCommandStyle);
  const topbarRemovalStyle=document.createElement('style');topbarRemovalStyle.textContent='main>#projectTopbar{display:none!important}main>#sidebarRoot{top:8px!important}main>.result{top:0!important}@media(max-width:900px){main>#sidebarRoot{top:auto!important}main>.result{top:auto!important}}';document.head.append(topbarRemovalStyle);
  const workspaceOverflowStyle=document.createElement('style');workspaceOverflowStyle.textContent='html body main>.result{box-sizing:border-box!important;width:calc(100% - 64px)!important;max-width:calc(100% - 64px)!important;overflow-x:hidden!important}html body.workspaceRailExpanded main>.result{width:calc(100% - 286px)!important;max-width:calc(100% - 286px)!important}html body main>.result>.resultWorkspace{box-sizing:border-box!important;width:100%!important;max-width:100%!important;min-width:0!important;overflow-x:hidden!important}html body main>.result>.resultWorkspace>#unplaced{box-sizing:border-box!important;max-width:100%!important;min-width:0!important;overflow-x:hidden!important}@media(max-width:900px){html body main>.result{width:100%!important;max-width:100%!important;overflow-x:hidden!important}html body main>.result>.resultWorkspace{width:100%!important;max-width:100%!important}}';document.head.append(workspaceOverflowStyle);
  const syncTopbarRemoval=()=>{if(window.matchMedia('(max-width:900px)').matches){root.style.removeProperty('top');result.style.removeProperty('top')}else{root.style.setProperty('top','8px','important');result.style.setProperty('top','0px','important')}};
  syncTopbarRemoval();
  window.addEventListener('resize',syncTopbarRemoval);
  const centerUnplacedDetails=()=>{const board=document.querySelector('#unplacedBoard'),pieces=[...board?.querySelectorAll(':scope > .piece')||[]];if(!board||!pieces.length)return;pieces.forEach(piece=>piece.style.removeProperty('margin-left'));const boardRect=board.getBoundingClientRect(),areaRect=board.parentElement?.getBoundingClientRect(),rects=pieces.map(piece=>piece.getBoundingClientRect()),left=Math.min(...rects.map(rect=>rect.left)),right=Math.max(...rects.map(rect=>rect.right)),visibleWidth=Math.max(0,Math.min(boardRect.width,(areaRect?.right??boardRect.right)-boardRect.left)),shift=(visibleWidth-(right-left))/2-(left-boardRect.left);if(Math.abs(shift)>1)pieces.forEach(piece=>piece.style.setProperty('margin-left',`${shift}px`))};
  const unplacedBoard=document.querySelector('#unplacedBoard');
  if(unplacedBoard){new MutationObserver(()=>requestAnimationFrame(centerUnplacedDetails)).observe(unplacedBoard,{childList:true});window.addEventListener('resize',centerUnplacedDetails);requestAnimationFrame(centerUnplacedDetails)}
  new MutationObserver(()=>requestAnimationFrame(centerUnplacedDetails)).observe(document.body,{attributes:true,attributeFilter:['class']});
  close();
})();
